//! Sync tests for the builtin method codegen table.
//!
//! Verifies that `BuiltinTable` registrations are consistent with
//! `ori_registry::BUILTIN_TYPES` and `ori_arc`. Catches three classes of drift:
//!
//! 1. **Phantom entries**: codegen claims to handle a method that no pipeline
//!    path ever emits (would never be called).
//! 2. **Coverage gaps**: registry exposes a method that codegen can't
//!    inline (falls through to runtime — acceptable but tracked).
//! 3. **Strategy coverage**: every `OpStrategy` variant in every registry type's
//!    `OpDefs` is handled by `emit_binary_op`/`emit_unary_op` dispatch.

use std::collections::HashSet;

use ori_registry::legacy_type_name;

use super::builtin_table;

/// Build the set of `(type_name, method_name)` pairs from the registry.
///
/// DEI-only methods are listed under `"DoubleEndedIterator"` to match
/// the naming convention used by the codegen table. Type names are normalized
/// to the legacy lowercase convention via [`legacy_type_name()`].
fn registry_method_set() -> HashSet<(&'static str, &'static str)> {
    let mut set = HashSet::new();
    for td in ori_registry::BUILTIN_TYPES {
        let type_name = legacy_type_name(td.name);
        for m in td.methods {
            if m.dei_only {
                set.insert(("DoubleEndedIterator", m.name));
            } else {
                set.insert((type_name, m.name));
            }
        }
    }
    set
}

/// Codegen aliases: method names used internally by the ARC pipeline
/// that map to canonical registry method names.
///
/// `"length"` is a property-access alias for `"len"`.
/// `"is_equal"` is the Eq trait method alias for `"equals"`.
const CODEGEN_ALIASES: &[(&str, &str)] = &[("length", "len"), ("is_equal", "equals")];

/// Methods that come from trait-system operator desugaring (e.g., `a < b` →
/// `a.is_less(b)`) rather than direct user method calls. These are valid
/// codegen targets but are NOT in `ori_registry` because the type checker
/// resolves them through the trait dispatch path, not the builtin method path.
///
/// Only applies to types that are NOT `Ordering` (Ordering has these
/// directly in the registry).
const TRAIT_DISPATCH_METHODS: &[&str] = &[
    "is_less",
    "is_greater",
    "is_less_or_equal",
    "is_greater_or_equal",
];

/// Methods generated by the ARC lowering or operator desugaring pipeline
/// that bypass the registry. These are valid codegen targets reached through
/// paths other than `resolve_builtin_method()`:
///
/// - Protocol builtins (`__iter_next`, `__collect_set`): derived from
///   [`ProtocolBuiltin::ALL`] — adding a new protocol variant here is automatic.
/// - `to_int`: Identity conversion (int → int in generic paths)
/// - `add`/`concat`: List operator desugaring (`list + list` → `list.add`)
fn arc_pipeline_methods() -> Vec<(&'static str, &'static str)> {
    use ori_ir::builtin_constants::protocol::ProtocolBuiltin;
    let mut methods: Vec<(&str, &str)> = Vec::new();

    // Protocol builtins — derive from the enum so new variants are automatic.
    // __index is NOT here: it's an ARC borrowing intrinsic, not a pipeline method.
    for &pb in ProtocolBuiltin::ALL {
        if pb == ProtocolBuiltin::Index {
            continue; // ARC borrowing intrinsic, not a BuiltinTable method
        }
        methods.push(("Iterator", pb.name()));
    }

    // Non-protocol pipeline methods.
    methods.push(("Ordering", "to_int"));
    methods.push(("int", "to_int"));
    methods.push(("list", "add"));
    methods.push(("list", "concat"));

    methods
}

/// Every `BuiltinTable` entry must be backed by a registry entry, a known
/// codegen alias, a trait-dispatch method, or an ARC-pipeline method.
///
/// Phantom entries indicate codegen for methods no pipeline path ever
/// emits — dead code in the dispatch table.
#[test]
fn no_phantom_builtin_entries() {
    let table = builtin_table();
    let registry: HashSet<(&str, &str)> = registry_method_set();
    let trait_methods: HashSet<&str> = TRAIT_DISPATCH_METHODS.iter().copied().collect();
    let arc_methods = arc_pipeline_methods();
    let arc_pipeline: HashSet<(&str, &str)> = arc_methods.iter().copied().collect();
    let aliases: std::collections::HashMap<&str, &str> = CODEGEN_ALIASES.iter().copied().collect();

    let mut phantom = Vec::new();

    for (type_name, method_name) in table.all_registered() {
        // Direct registry match
        if registry.contains(&(type_name, method_name)) {
            continue;
        }

        // Codegen alias: check if canonical name is in registry for this type
        if let Some(&canonical) = aliases.get(method_name) {
            if registry.contains(&(type_name, canonical)) {
                continue;
            }
        }

        // Trait-dispatch method (comparison predicates — not for Ordering,
        // which has them directly in the registry)
        if type_name != "Ordering" && trait_methods.contains(method_name) {
            continue;
        }

        // ARC-pipeline method (specific type+method pairs)
        if arc_pipeline.contains(&(type_name, method_name)) {
            continue;
        }

        phantom.push(format!("  ({type_name}, {method_name})"));
    }

    assert!(
        phantom.is_empty(),
        "BuiltinTable has {} phantom entries (no registry backing):\n{}",
        phantom.len(),
        phantom.join("\n"),
    );
}

/// Track codegen coverage of registry-visible methods.
///
/// This test does NOT fail on missing coverage — many registry methods are
/// intentionally handled by runtime calls rather than inline LLVM IR.
/// The test fails only if coverage drops below a minimum threshold,
/// which would indicate an accidental regression.
#[test]
fn builtin_coverage_above_threshold() {
    let table = builtin_table();
    let registry = registry_method_set();

    // Types that the codegen supports (have builtin_type_name() mappings)
    let codegen_types: HashSet<&str> = [
        "int", "float", "bool", "char", "byte", "str", "Duration", "Size", "Ordering", "list",
        "map", "Set", "tuple", "Option", "Result", "range", "Iterator", "Channel", "error",
    ]
    .into_iter()
    .collect();

    let codegen_registry: Vec<_> = registry
        .iter()
        .filter(|(type_name, _)| codegen_types.contains(type_name))
        .collect();

    let mut covered = 0;
    let mut uncovered = Vec::new();

    for &(type_name, method_name) in &codegen_registry {
        if table.has(type_name, method_name) {
            covered += 1;
        } else {
            uncovered.push(format!("  ({type_name}, {method_name})"));
        }
    }

    let total = codegen_registry.len();
    let pct = if total > 0 {
        covered * 100 / total
    } else {
        100
    };

    // Minimum coverage threshold — ratcheted to current level minus margin.
    // Update when coverage increases. Current: ~40% after iterator/option/result gap fill.
    let min_pct = 35;
    assert!(
        pct >= min_pct,
        "Builtin codegen coverage dropped to {pct}% ({covered}/{total}), \
         minimum is {min_pct}%. Uncovered:\n{}",
        uncovered.join("\n"),
    );
}

/// For each method with `backend_required: true`, verify that the LLVM
/// `BuiltinTable` has an entry. Methods with `backend_required: false`
/// are intentionally exempt (they fall through to runtime calls).
///
/// This test uses a ceiling: the number of missing methods must not grow.
/// As LLVM codegen is added for more methods, lower the ceiling.
/// Target: 0 (all `backend_required` methods have LLVM handlers).
#[test]
fn backend_required_methods_in_llvm() {
    let table = builtin_table();

    let mut missing = Vec::new();

    for type_def in ori_registry::BUILTIN_TYPES {
        let type_name = legacy_type_name(type_def.name);
        for method in type_def.methods {
            if !method.backend_required {
                continue;
            }

            if method.dei_only {
                if !table.has("DoubleEndedIterator", method.name) {
                    missing.push(format!("DoubleEndedIterator.{}", method.name));
                }
            } else if !table.has(type_name, method.name) {
                missing.push(format!("{type_name}.{}", method.name));
            }
        }
    }

    // Ceiling: must not grow. Lower as methods are implemented.
    let ceiling = 140;
    assert!(
        missing.len() <= ceiling,
        "backend_required methods without LLVM handlers grew to {} (ceiling: {ceiling}). \
         Implement the LLVM handler or set backend_required: false.\n\
         Missing:\n{}",
        missing.len(),
        missing.join("\n"),
    );
}

/// Every type with operators in the registry must have its `OpStrategy`
/// handled by `emit_binary_op`/`emit_unary_op` dispatch.
///
/// This verifies that no `OpStrategy` variant slips through unhandled:
/// every non-`Unsupported` strategy must be in the set of strategies
/// that the dispatch code explicitly matches.
#[test]
fn registry_op_strategies_cover_all_operators() {
    use ori_registry::{OpStrategy, BUILTIN_TYPES};

    for type_def in BUILTIN_TYPES {
        let ops = &type_def.operators;
        for (field_name, strategy) in [
            ("add", ops.add),
            ("sub", ops.sub),
            ("mul", ops.mul),
            ("div", ops.div),
            ("rem", ops.rem),
            ("floor_div", ops.floor_div),
            ("eq", ops.eq),
            ("neq", ops.neq),
            ("lt", ops.lt),
            ("gt", ops.gt),
            ("lt_eq", ops.lt_eq),
            ("gt_eq", ops.gt_eq),
            ("neg", ops.neg),
            ("not", ops.not),
            ("bit_and", ops.bit_and),
            ("bit_or", ops.bit_or),
            ("bit_xor", ops.bit_xor),
            ("bit_not", ops.bit_not),
            ("shl", ops.shl),
            ("shr", ops.shr),
        ] {
            match strategy {
                OpStrategy::Unsupported
                | OpStrategy::IntInstr
                | OpStrategy::FloatInstr
                | OpStrategy::UnsignedCmp
                | OpStrategy::BoolLogic => {} // Unsupported or handled by emit_{int,float,unsigned,bool}_*_op
                OpStrategy::RuntimeCall { fn_name, .. } => {
                    assert!(
                        !fn_name.is_empty(),
                        "{}.operators.{field_name} has empty RuntimeCall fn_name",
                        type_def.name
                    );
                }
            }
        }
    }
}

/// All registry iterator methods (except protocol methods `next` and
/// `next_back`) must have entries in the `BuiltinTable`.
///
/// Protocol methods are intercepted by `try_emit_protocol` before reaching
/// builtin method dispatch — they are NOT in the registry and do not need
/// `BuiltinTable` entries.
///
/// This is stricter than `backend_required_methods_in_llvm` — it verifies
/// ALL iterator methods are registered, regardless of `backend_required`.
#[test]
fn iterator_emit_covers_all_registry_methods() {
    let table = builtin_table();

    let mut missing = Vec::new();

    for method in ori_registry::methods_for(ori_registry::TypeTag::Iterator) {
        // Protocol methods are handled by try_emit_protocol, not BuiltinTable
        if method.name == "next" || method.name == "next_back" {
            continue;
        }

        let type_name = if method.dei_only {
            "DoubleEndedIterator"
        } else {
            "Iterator"
        };

        if !table.has(type_name, method.name) {
            missing.push(format!("{type_name}.{}", method.name));
        }
    }

    assert!(
        missing.is_empty(),
        "Registry iterator methods missing from BuiltinTable ({} missing):\n{}",
        missing.len(),
        missing.join("\n"),
    );
}

/// For each Option method with `backend_required: true`, verify the LLVM
/// `BuiltinTable` has an entry. Forward-looking guard: if a future registry
/// addition sets `backend_required: true`, this test catches the missing handler.
#[test]
fn option_emit_covers_backend_required_methods() {
    let table = builtin_table();
    let mut missing = Vec::new();

    for method in ori_registry::methods_for(ori_registry::TypeTag::Option) {
        if !method.backend_required {
            continue;
        }
        if !table.has("Option", method.name) {
            missing.push(format!("Option.{}", method.name));
        }
    }

    assert!(
        missing.is_empty(),
        "Option backend_required methods missing from BuiltinTable:\n{}",
        missing.join("\n"),
    );
}

/// For each Result method with `backend_required: true`, verify the LLVM
/// `BuiltinTable` has an entry.
#[test]
fn result_emit_covers_backend_required_methods() {
    let table = builtin_table();
    let mut missing = Vec::new();

    for method in ori_registry::methods_for(ori_registry::TypeTag::Result) {
        if !method.backend_required {
            continue;
        }
        if !table.has("Result", method.name) {
            missing.push(format!("Result.{}", method.name));
        }
    }

    assert!(
        missing.is_empty(),
        "Result backend_required methods missing from BuiltinTable:\n{}",
        missing.join("\n"),
    );
}
