//! Sync tests for the builtin method codegen table.
//!
//! Verifies that `BuiltinTable` registrations are consistent with
//! `TYPECK_BUILTIN_METHODS` from `ori_types` and `ori_arc`. Catches three
//! classes of drift:
//!
//! 1. **Phantom entries**: codegen claims to handle a method that no pipeline
//!    path ever emits (would never be called).
//! 2. **Coverage gaps**: type checker exposes a method that codegen can't
//!    inline (falls through to runtime — acceptable but tracked).
//! 3. **Ownership mismatch**: a COW method in `ori_arc`'s consuming sets has
//!    `receiver_borrowed: true` in the LLVM table (would break COW codegen).

use std::collections::HashSet;

use ori_ir::StringInterner;
use ori_types::TYPECK_BUILTIN_METHODS;

use super::{borrowing_names_from_table, builtin_table};

/// Codegen aliases: method names used internally by the ARC pipeline
/// that map to canonical TYPECK method names.
///
/// `"length"` is a property-access alias for `"len"`.
/// `"is_equal"` is the Eq trait method alias for `"equals"`.
const CODEGEN_ALIASES: &[(&str, &str)] = &[("length", "len"), ("is_equal", "equals")];

/// Methods that come from trait-system operator desugaring (e.g., `a < b` →
/// `a.is_less(b)`) rather than direct user method calls. These are valid
/// codegen targets but are NOT listed in `TYPECK_BUILTIN_METHODS` because
/// the type checker resolves them through the trait dispatch path, not the
/// builtin method path.
///
/// Only applies to types that are NOT `Ordering` (Ordering has these
/// directly in TYPECK).
const TRAIT_DISPATCH_METHODS: &[&str] = &[
    "is_less",
    "is_greater",
    "is_less_or_equal",
    "is_greater_or_equal",
];

/// Methods generated by the ARC lowering or operator desugaring pipeline
/// that bypass `TYPECK_BUILTIN_METHODS`. These are valid codegen targets
/// reached through paths other than `resolve_builtin_method()`:
///
/// - Protocol builtins (`__iter_next`, `__collect_set`): derived from
///   [`ProtocolBuiltin::ALL`] — adding a new protocol variant here is automatic.
/// - `to_int`: Identity conversion (int → int in generic paths)
/// - `add`/`concat`: List operator desugaring (`list + list` → `list.add`)
fn arc_pipeline_methods() -> Vec<(&'static str, &'static str)> {
    use ori_ir::builtin_constants::protocol::ProtocolBuiltin;
    let mut methods: Vec<(&str, &str)> = Vec::new();

    // Protocol builtins — derive from the enum so new variants are automatic.
    // __index is NOT here: it's an ARC borrowing intrinsic, not a pipeline method
    // (it doesn't have a receiver type in TYPECK_BUILTIN_METHODS).
    for &pb in ProtocolBuiltin::ALL {
        if pb == ProtocolBuiltin::Index {
            continue; // Handled in arc_borrowing_intrinsics()
        }
        methods.push(("Iterator", pb.name()));
    }

    // Non-protocol pipeline methods.
    methods.push(("Ordering", "to_int"));
    methods.push(("int", "to_int"));
    methods.push(("list", "add"));
    methods.push(("list", "concat"));

    methods
}

/// Every `BuiltinTable` entry must be backed by a TYPECK entry, a known
/// codegen alias, a trait-dispatch method, or an ARC-pipeline method.
///
/// Phantom entries indicate codegen for methods no pipeline path ever
/// emits — dead code in the dispatch table.
#[test]
fn no_phantom_builtin_entries() {
    let table = builtin_table();
    let typeck: HashSet<(&str, &str)> = TYPECK_BUILTIN_METHODS.iter().copied().collect();
    let trait_methods: HashSet<&str> = TRAIT_DISPATCH_METHODS.iter().copied().collect();
    let arc_methods = arc_pipeline_methods();
    let arc_pipeline: HashSet<(&str, &str)> = arc_methods.iter().copied().collect();
    let aliases: std::collections::HashMap<&str, &str> = CODEGEN_ALIASES.iter().copied().collect();

    let mut phantom = Vec::new();

    for (type_name, method_name) in table.all_registered() {
        // Direct TYPECK match
        if typeck.contains(&(type_name, method_name)) {
            continue;
        }

        // Codegen alias: check if canonical name is in TYPECK for this type
        if let Some(&canonical) = aliases.get(method_name) {
            if typeck.contains(&(type_name, canonical)) {
                continue;
            }
        }

        // Trait-dispatch method (comparison predicates — not for Ordering,
        // which has them directly in TYPECK)
        if type_name != "Ordering" && trait_methods.contains(method_name) {
            continue;
        }

        // ARC-pipeline method (specific type+method pairs)
        if arc_pipeline.contains(&(type_name, method_name)) {
            continue;
        }

        phantom.push(format!("  ({type_name}, {method_name})"));
    }

    assert!(
        phantom.is_empty(),
        "BuiltinTable has {} phantom entries (no TYPECK backing):\n{}",
        phantom.len(),
        phantom.join("\n"),
    );
}

/// Track codegen coverage of TYPECK-visible methods.
///
/// This test does NOT fail on missing coverage — many TYPECK methods are
/// intentionally handled by runtime calls rather than inline LLVM IR.
/// The test fails only if coverage drops below a minimum threshold,
/// which would indicate an accidental regression.
#[test]
fn builtin_coverage_above_threshold() {
    let table = builtin_table();

    // Types that the codegen supports (have builtin_type_name() mappings)
    let codegen_types: HashSet<&str> = [
        "int", "float", "bool", "char", "byte", "str", "Duration", "Size", "Ordering", "list",
        "map", "Set", "tuple", "Option", "Result", "range", "Iterator", "Channel", "error",
    ]
    .into_iter()
    .collect();

    let codegen_typeck: Vec<_> = TYPECK_BUILTIN_METHODS
        .iter()
        .filter(|(type_name, _)| codegen_types.contains(type_name))
        .collect();

    let mut covered = 0;
    let mut uncovered = Vec::new();

    for &&(type_name, method_name) in &codegen_typeck {
        if table.has(type_name, method_name) {
            covered += 1;
        } else {
            uncovered.push(format!("  ({type_name}, {method_name})"));
        }
    }

    let total = codegen_typeck.len();
    let pct = if total > 0 {
        covered * 100 / total
    } else {
        100
    };

    // Minimum coverage threshold — raise as more methods are migrated
    let min_pct = 25;
    assert!(
        pct >= min_pct,
        "Builtin codegen coverage dropped to {pct}% ({covered}/{total}), \
         minimum is {min_pct}%. Uncovered:\n{}",
        uncovered.join("\n"),
    );
}

/// ARC pipeline intrinsics that borrow their receiver but bypass the
/// Protocol builtins with all-borrowed semantics that appear in
/// `ori_arc::BORROWING_METHOD_NAMES` but bypass the `BuiltinTable`
/// dispatch chain. These are intercepted at the `Apply` instruction
/// level in `apply_protocols.rs`, not through `try_emit_builtin_method`.
///
/// Derived from [`ProtocolBuiltin::ALL`] — adding a new all-borrowed
/// protocol variant here is automatic.
fn arc_borrowing_intrinsics() -> Vec<&'static str> {
    use ori_ir::builtin_constants::protocol::{ProtocolArgOwnership, ProtocolBuiltin};
    ProtocolBuiltin::ALL
        .iter()
        .filter(|pb| {
            pb.arg_ownership()
                .iter()
                .all(|o| *o == ProtocolArgOwnership::Borrowed)
        })
        .map(|pb| pb.name())
        .collect()
}

/// The canonical borrowing-builtin set in `ori_arc` must match the effective
/// set derived from the LLVM `BuiltinTable`.
///
/// This catches drift: if a new builtin method is added to the table with
/// `borrow: true` but not added to `ori_arc::BORROWING_METHOD_NAMES`, borrow
/// inference won't know about it. Conversely, if a method is removed from the
/// table but left in `ori_arc`, borrow inference will make incorrect assumptions.
///
/// ARC pipeline intrinsics (e.g., `__index`) are excluded — they borrow their
/// receiver but are intercepted before `BuiltinTable` dispatch.
#[test]
fn borrowing_builtins_sync_with_ori_arc() {
    let interner = StringInterner::default();

    // Set derived from LLVM BuiltinTable (codegen ground truth)
    let table_set = borrowing_names_from_table(&interner);

    // Set from ori_arc (canonical source for borrow inference)
    let arc_set = ori_arc::borrowing_builtin_names(&interner);

    // Exclude ARC pipeline intrinsics from the arc_set for comparison
    let borrowing_intrinsics = arc_borrowing_intrinsics();
    let intrinsics: HashSet<_> = borrowing_intrinsics.iter().copied().collect();
    let arc_set_filtered: rustc_hash::FxHashSet<_> = arc_set
        .iter()
        .filter(|n| !intrinsics.contains(interner.lookup(**n)))
        .copied()
        .collect();

    // Find mismatches
    let in_table_not_arc: Vec<_> = table_set
        .difference(&arc_set_filtered)
        .map(|n| interner.lookup(*n).to_string())
        .collect();

    let in_arc_not_table: Vec<_> = arc_set_filtered
        .difference(&table_set)
        .map(|n| interner.lookup(*n).to_string())
        .collect();

    assert!(
        in_table_not_arc.is_empty() && in_arc_not_table.is_empty(),
        "Borrowing builtin sets out of sync!\n\
         In LLVM BuiltinTable but not ori_arc: {in_table_not_arc:?}\n\
         In ori_arc but not LLVM BuiltinTable: {in_arc_not_table:?}\n\
         Update ori_arc::borrow::builtins::BORROWING_METHOD_NAMES to match.",
    );
}

/// COW methods in `ori_arc` must not be marked as borrowing in the LLVM
/// `BuiltinTable` for collection types.
///
/// This catches drift for Section 07.5 (COW Check Elimination): when the
/// emitter starts consuming `CowAnnotations`, a method in `ori_arc`'s
/// `consuming_receiver_builtin_names` or `consuming_receiver_only_builtin_names`
/// that has `receiver_borrowed: true` in the LLVM table would produce
/// incorrect RC ownership — the receiver would be borrowed when it should be
/// consumed for COW.
///
/// Only checks collection types (`list`, `map`, `Set`) because the `ori_arc`
/// consuming sets are name-only (not type-qualified). Methods like `reverse`
/// and `concat` are COW for lists but borrowing for other types (`Ordering`,
/// `str`). The type check happens at the RC insertion call site.
#[test]
fn consuming_builtins_sync_with_ori_arc() {
    let interner = StringInterner::default();
    let table = builtin_table();

    // Types where COW semantics apply
    let cow_types: HashSet<&str> = ["list", "map", "Set"].into_iter().collect();

    // COW method sets from ori_arc (drive uniqueness analysis)
    let consuming = ori_arc::consuming_receiver_builtin_names(&interner);
    let consuming_only = ori_arc::consuming_receiver_only_builtin_names(&interner);

    let mut mismatches = Vec::new();

    for (type_name, method_name) in table.all_registered() {
        if !cow_types.contains(type_name) {
            continue;
        }

        let name = interner.intern(method_name);
        let is_cow = consuming.contains(&name) || consuming_only.contains(&name);

        if !is_cow {
            continue;
        }

        if let Some(reg) = table.lookup(type_name, method_name) {
            if reg.receiver_borrowed {
                mismatches.push(format!(
                    "  ({type_name}, {method_name}): ori_arc says consuming (COW), \
                     but BuiltinTable has receiver_borrowed=true"
                ));
            }
        }
    }

    assert!(
        mismatches.is_empty(),
        "Consuming-receiver builtin sets out of sync!\n\
         Methods in ori_arc's COW sets must have receiver_borrowed=false \
         in the LLVM BuiltinTable for collection types:\n{}\n\
         Either update the LLVM table or remove from ori_arc's consuming sets.",
        mismatches.join("\n"),
    );
}
