//! Sync tests for the builtin method codegen table.
//!
//! Verifies that `BuiltinTable` registrations are consistent with
//! `TYPECK_BUILTIN_METHODS` from `ori_types`. Catches two classes of drift:
//!
//! 1. **Phantom entries**: codegen claims to handle a method that no pipeline
//!    path ever emits (would never be called).
//! 2. **Coverage gaps**: type checker exposes a method that codegen can't
//!    inline (falls through to runtime — acceptable but tracked).

use std::collections::HashSet;

use ori_types::TYPECK_BUILTIN_METHODS;

use super::builtin_table;

/// Codegen aliases: method names used internally by the ARC pipeline
/// that map to canonical TYPECK method names.
///
/// `"length"` is a property-access alias for `"len"`.
/// `"is_equal"` is the Eq trait method alias for `"equals"`.
const CODEGEN_ALIASES: &[(&str, &str)] = &[("length", "len"), ("is_equal", "equals")];

/// Methods that come from trait-system operator desugaring (e.g., `a < b` →
/// `a.is_less(b)`) rather than direct user method calls. These are valid
/// codegen targets but are NOT listed in `TYPECK_BUILTIN_METHODS` because
/// the type checker resolves them through the trait dispatch path, not the
/// builtin method path.
///
/// Only applies to types that are NOT `Ordering` (Ordering has these
/// directly in TYPECK).
const TRAIT_DISPATCH_METHODS: &[&str] = &[
    "is_less",
    "is_greater",
    "is_less_or_equal",
    "is_greater_or_equal",
];

/// Methods generated by the ARC lowering or operator desugaring pipeline
/// that bypass `TYPECK_BUILTIN_METHODS`. These are valid codegen targets
/// reached through paths other than `resolve_builtin_method()`:
///
/// - `__iter_next`: Low-level iteration protocol (ARC lowering)
/// - `to_int`: Identity conversion (int → int in generic paths)
/// - `add`/`concat`: List operator desugaring (`list + list` → `list.add`)
const ARC_PIPELINE_METHODS: &[(&str, &str)] = &[
    ("Iterator", "__iter_next"),
    ("Ordering", "to_int"),
    ("int", "to_int"),
    ("list", "add"),
    ("list", "concat"),
];

/// Every `BuiltinTable` entry must be backed by a TYPECK entry, a known
/// codegen alias, a trait-dispatch method, or an ARC-pipeline method.
///
/// Phantom entries indicate codegen for methods no pipeline path ever
/// emits — dead code in the dispatch table.
#[test]
fn no_phantom_builtin_entries() {
    let table = builtin_table();
    let typeck: HashSet<(&str, &str)> = TYPECK_BUILTIN_METHODS.iter().copied().collect();
    let trait_methods: HashSet<&str> = TRAIT_DISPATCH_METHODS.iter().copied().collect();
    let arc_pipeline: HashSet<(&str, &str)> = ARC_PIPELINE_METHODS.iter().copied().collect();
    let aliases: std::collections::HashMap<&str, &str> = CODEGEN_ALIASES.iter().copied().collect();

    let mut phantom = Vec::new();

    for (type_name, method_name) in table.all_registered() {
        // Direct TYPECK match
        if typeck.contains(&(type_name, method_name)) {
            continue;
        }

        // Codegen alias: check if canonical name is in TYPECK for this type
        if let Some(&canonical) = aliases.get(method_name) {
            if typeck.contains(&(type_name, canonical)) {
                continue;
            }
        }

        // Trait-dispatch method (comparison predicates — not for Ordering,
        // which has them directly in TYPECK)
        if type_name != "Ordering" && trait_methods.contains(method_name) {
            continue;
        }

        // ARC-pipeline method (specific type+method pairs)
        if arc_pipeline.contains(&(type_name, method_name)) {
            continue;
        }

        phantom.push(format!("  ({type_name}, {method_name})"));
    }

    assert!(
        phantom.is_empty(),
        "BuiltinTable has {} phantom entries (no TYPECK backing):\n{}",
        phantom.len(),
        phantom.join("\n"),
    );
}

/// Track codegen coverage of TYPECK-visible methods.
///
/// This test does NOT fail on missing coverage — many TYPECK methods are
/// intentionally handled by runtime calls rather than inline LLVM IR.
/// The test fails only if coverage drops below a minimum threshold,
/// which would indicate an accidental regression.
#[test]
fn builtin_coverage_above_threshold() {
    let table = builtin_table();

    // Types that the codegen supports (have builtin_type_name() mappings)
    let codegen_types: HashSet<&str> = [
        "int", "float", "bool", "char", "byte", "str", "Duration", "Size", "Ordering", "list",
        "map", "Set", "tuple", "Option", "Result", "range", "Iterator", "Channel", "error",
    ]
    .into_iter()
    .collect();

    let codegen_typeck: Vec<_> = TYPECK_BUILTIN_METHODS
        .iter()
        .filter(|(type_name, _)| codegen_types.contains(type_name))
        .collect();

    let mut covered = 0;
    let mut uncovered = Vec::new();

    for &&(type_name, method_name) in &codegen_typeck {
        if table.has(type_name, method_name) {
            covered += 1;
        } else {
            uncovered.push(format!("  ({type_name}, {method_name})"));
        }
    }

    let total = codegen_typeck.len();
    let pct = if total > 0 {
        covered * 100 / total
    } else {
        100
    };

    // Minimum coverage threshold — raise as more methods are migrated
    let min_pct = 25;
    assert!(
        pct >= min_pct,
        "Builtin codegen coverage dropped to {pct}% ({covered}/{total}), \
         minimum is {min_pct}%. Uncovered:\n{}",
        uncovered.join("\n"),
    );
}
