//! List construction, access, mutation, and OOB-panicking accessors.

use super::super::types::{Attr, RtFn, Ty};

pub(in crate::codegen::runtime_decl) static LIST: &[RtFn] = &[
    // List — extern "C" unless noted
    RtFn {
        name: "ori_list_alloc_data",
        params: &[Ty::I64, Ty::I64],
        ret: Some(Ty::Ptr),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_free_data",
        params: &[Ty::Ptr, Ty::I64, Ty::I64],
        ret: None,
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_new",
        params: &[Ty::I64, Ty::I64],
        ret: Some(Ty::Ptr),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_free",
        params: &[Ty::Ptr, Ty::I64],
        ret: None,
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_len",
        params: &[Ty::Ptr],
        ret: Some(Ty::I64),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_push",
        params: &[Ty::Ptr, Ty::Ptr, Ty::I64],
        ret: None,
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_take",
        params: &[Ty::Ptr, Ty::Ptr],
        ret: None,
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_box_new",
        params: &[Ty::I64, Ty::I64, Ty::Ptr],
        ret: Some(Ty::Ptr),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_push_cow",
        // data, len, cap, elem_ptr, elem_size, elem_align, inc_fn, cow_mode, out_ptr
        params: &[
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I32,
            Ty::Ptr,
        ],
        ret: None,
        attrs: &[Attr::Nounwind, Attr::NoaliasLastParam],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_pop_cow",
        // data, len, cap, elem_size, elem_align, inc_fn, cow_mode, out_ptr
        params: &[
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I32,
            Ty::Ptr,
        ],
        ret: None,
        attrs: &[Attr::Nounwind, Attr::NoaliasLastParam],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_set_cow",
        // data, len, cap, index, elem_ptr, elem_size, elem_align, inc_fn, cow_mode, out_ptr
        params: &[
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I32,
            Ty::Ptr,
        ],
        ret: None,
        attrs: &[Attr::Nounwind, Attr::NoaliasLastParam],
        jit_allowed: true,
    },
    // extern "C-unwind" — panics on out-of-bounds key (matches ori_list_get)
    RtFn {
        name: "ori_list_updated_cow",
        // data, len, cap, index, elem_ptr, elem_size, elem_align, inc_fn, dec_fn, cow_mode, out_ptr
        params: &[
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::Ptr,
            Ty::I32,
            Ty::Ptr,
        ],
        ret: None,
        attrs: &[Attr::NoaliasLastParam],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_insert_cow",
        // data, len, cap, index, elem_ptr, elem_size, elem_align, inc_fn, cow_mode, out_ptr
        params: &[
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I32,
            Ty::Ptr,
        ],
        ret: None,
        attrs: &[Attr::Nounwind, Attr::NoaliasLastParam],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_remove_cow",
        // data, len, cap, index, elem_size, elem_align, inc_fn, cow_mode, out_ptr
        params: &[
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I32,
            Ty::Ptr,
        ],
        ret: None,
        attrs: &[Attr::Nounwind, Attr::NoaliasLastParam],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_concat_cow",
        // data1, len1, cap1, data2, len2, cap2, elem_size, elem_align, inc_fn, cow_mode, out_ptr
        params: &[
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I32,
            Ty::Ptr,
        ],
        ret: None,
        attrs: &[Attr::Nounwind, Attr::NoaliasLastParam],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_reverse_cow",
        // data, len, cap, elem_size, elem_align, inc_fn, cow_mode, out_ptr
        params: &[
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I32,
            Ty::Ptr,
        ],
        ret: None,
        attrs: &[Attr::Nounwind, Attr::NoaliasLastParam],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_sort_cow",
        // data, len, cap, elem_size, elem_align, compare_fn, inc_fn, cow_mode, out_ptr
        params: &[
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::Ptr,
            Ty::I32,
            Ty::Ptr,
        ],
        ret: None,
        attrs: &[Attr::Nounwind, Attr::NoaliasLastParam],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_sort_stable_cow",
        // Same signature as ori_list_sort_cow (stable TimSort variant, with cow_mode)
        params: &[
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::Ptr,
            Ty::I32,
            Ty::Ptr,
        ],
        ret: None,
        attrs: &[Attr::Nounwind, Attr::NoaliasLastParam],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_first",
        params: &[Ty::Ptr, Ty::I64, Ty::I64, Ty::Ptr],
        ret: None,
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_last",
        params: &[Ty::Ptr, Ty::I64, Ty::I64, Ty::Ptr],
        ret: None,
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    // extern "C-unwind" — panics on out-of-bounds access
    RtFn {
        name: "ori_list_get",
        // (data, len, index, elem_size, out_ptr) — panics on OOB
        params: &[Ty::Ptr, Ty::I64, Ty::I64, Ty::I64, Ty::Ptr],
        ret: None,
        attrs: &[],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_contains_int",
        params: &[Ty::Ptr, Ty::I64, Ty::I64],
        ret: Some(Ty::I64),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_contains_str",
        params: &[Ty::Ptr, Ty::I64, Ty::Ptr],
        ret: Some(Ty::I64),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_concat",
        // data1, len1, data2, len2, elem_size, elem_align, out_ptr
        params: &[
            Ty::Ptr,
            Ty::I64,
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
        ],
        ret: None,
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_reverse",
        // data, len, elem_size, elem_align, out_ptr
        params: &[Ty::Ptr, Ty::I64, Ty::I64, Ty::I64, Ty::Ptr],
        ret: None,
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
];
