//! String iteration, comparison (incl. list/map deep-eq), operations, property access, conversion, debug formatting, methods.

use super::super::types::{Attr, RtFn, Ty};

pub(in crate::codegen::runtime_decl) static STRINGS: &[RtFn] = &[
    // String iteration — extern "C"
    RtFn {
        name: "ori_str_chars",
        params: &[Ty::Ptr, Ty::I64, Ty::Ptr],
        ret: None,
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_split",
        // (str_ptr, str_len, str_cap, sep_ptr, sep_len, elem_dec_fn, out_ptr)
        params: &[
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::I64,
            Ty::Ptr,
            Ty::Ptr,
        ],
        ret: None,
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    // Comparison — pure functions, cannot panic
    RtFn {
        name: "ori_compare_int",
        params: &[Ty::I64, Ty::I64],
        ret: Some(Ty::I32),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_min_int",
        params: &[Ty::I64, Ty::I64],
        ret: Some(Ty::I64),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_max_int",
        params: &[Ty::I64, Ty::I64],
        ret: Some(Ty::I64),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    // String operations — all extern "C"
    RtFn {
        name: "ori_str_concat",
        params: &[Ty::Ptr, Ty::Ptr],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_eq",
        params: &[Ty::Ptr, Ty::Ptr],
        ret: Some(Ty::Bool),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_list_eq_scalar",
        params: &[Ty::Ptr, Ty::Ptr, Ty::I64],
        ret: Some(Ty::Bool),
        attrs: &[Attr::Nounwind],
        jit_allowed: false,
    },
    // ori_list_eq_deep(a: ptr, b: ptr, elem_size, elem_eq) -> bool
    RtFn {
        name: "ori_list_eq_deep",
        params: &[Ty::Ptr, Ty::Ptr, Ty::I64, Ty::Ptr],
        ret: Some(Ty::Bool),
        attrs: &[Attr::Nounwind],
        jit_allowed: false,
    },
    // ori_map_eq(a: ptr, b: ptr, key_size, val_size, key_eq, key_hash, val_eq) -> bool
    RtFn {
        name: "ori_map_eq",
        params: &[
            Ty::Ptr,
            Ty::Ptr,
            Ty::I64,
            Ty::I64,
            Ty::Ptr,
            Ty::Ptr,
            Ty::Ptr,
        ],
        ret: Some(Ty::Bool),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    // ori_map_hash(m: ptr, key_size, val_size, key_hash, val_hash) -> i64
    RtFn {
        name: "ori_map_hash",
        params: &[Ty::Ptr, Ty::I64, Ty::I64, Ty::Ptr, Ty::Ptr],
        ret: Some(Ty::I64),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_ne",
        params: &[Ty::Ptr, Ty::Ptr],
        ret: Some(Ty::Bool),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_compare",
        params: &[Ty::Ptr, Ty::Ptr],
        ret: Some(Ty::I8),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_hash",
        params: &[Ty::Ptr],
        ret: Some(Ty::I64),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    // String property access (SSO-safe, cannot panic)
    RtFn {
        name: "ori_str_len",
        params: &[Ty::Ptr],
        ret: Some(Ty::I64),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_data",
        params: &[Ty::Ptr],
        ret: Some(Ty::Ptr),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    // String iteration (char-by-char, pure read)
    RtFn {
        name: "ori_str_next_char",
        params: &[Ty::Ptr, Ty::I64, Ty::I64],
        ret: Some(Ty::CharResult),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    // Type conversion — all extern "C"
    RtFn {
        name: "ori_str_from_raw",
        params: &[Ty::Ptr, Ty::I64],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_from_int",
        params: &[Ty::I64],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_from_duration",
        params: &[Ty::I64],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_from_size",
        params: &[Ty::I64],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_from_bool",
        params: &[Ty::Bool],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_from_ordering",
        params: &[Ty::I64],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_from_float",
        params: &[Ty::F64],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    // String debug formatting — Debug semantics (quotes + escaping)
    RtFn {
        name: "ori_str_debug_format",
        params: &[Ty::Ptr],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_escape_control",
        params: &[Ty::Ptr],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_from_char",
        params: &[Ty::I32],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_char_is_alpha",
        params: &[Ty::I32],
        ret: Some(Ty::Bool),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_char_debug_format",
        params: &[Ty::I32],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_byte_debug_format",
        params: &[Ty::I64],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    // String methods — all extern "C"
    RtFn {
        name: "ori_str_contains",
        params: &[Ty::Ptr, Ty::Ptr],
        ret: Some(Ty::Bool),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_starts_with",
        params: &[Ty::Ptr, Ty::Ptr],
        ret: Some(Ty::Bool),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_ends_with",
        params: &[Ty::Ptr, Ty::Ptr],
        ret: Some(Ty::Bool),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_trim",
        params: &[Ty::Ptr],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_to_uppercase",
        params: &[Ty::Ptr],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_to_lowercase",
        params: &[Ty::Ptr],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_replace",
        params: &[Ty::Ptr, Ty::Ptr, Ty::Ptr],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
    RtFn {
        name: "ori_str_repeat",
        params: &[Ty::Ptr, Ty::I64],
        ret: Some(Ty::Str),
        attrs: &[Attr::Nounwind],
        jit_allowed: true,
    },
];
