//! Derived trait implementation registration (Pass 0d).
//!
//! Processes `#[derive(Eq, Clone, ...)]` attributes on type declarations.
//! Validates derivability constraints (supertrait requirements, sum type
//! restrictions, field trait satisfaction) and generates method signatures
//! so the type checker can resolve derived method calls.

use ori_ir::{DerivedImplId, DerivedMethodShape, DerivedTrait, ExprId, Name, Span};
use rustc_hash::{FxHashMap, FxHashSet};

use super::type_resolution::{collect_generic_params, resolve_parsed_type_simple};
use crate::{
    AcceptedDerivedImpl, FunctionSig, Idx, ImplEntry, ImplMethodDef, ImplSpecificity,
    ModuleChecker, Tag, TypeCheckError,
};

/// Register derived trait implementations.
pub fn register_derived_impls(checker: &mut ModuleChecker<'_>, module: &ori_ir::Module) {
    for type_decl in &module.types {
        for derive in &type_decl.derives {
            register_derived_impl(checker, type_decl, *derive);
        }
    }
}

/// Generate and register an implementation for a derived trait.
///
/// Creates an impl block with proper method signatures so the type checker can
/// resolve derived method calls. The actual method bodies are generated by the
/// evaluator (interpreter) or LLVM codegen — the type checker only needs the
/// signatures for return type resolution.
pub(super) fn register_derived_impl(
    checker: &mut ModuleChecker<'_>,
    type_decl: &ori_ir::TypeDecl,
    trait_name: Name,
) {
    // 0. Reject non-derivable traits (E2033)
    let trait_kind = {
        let trait_str = checker.interner().lookup(trait_name);
        if let Some(kind) = DerivedTrait::from_name(trait_str) {
            kind
        } else {
            checker.push_error(TypeCheckError::trait_not_derivable(
                type_decl.span,
                trait_name,
            ));
            return;
        }
    };

    // 0a. Reject derives on sum types when the trait doesn't support it (E2028)
    if !trait_kind.supports_sum_types() && matches!(type_decl.kind, ori_ir::TypeDeclKind::Sum(_)) {
        checker.push_error(TypeCheckError::cannot_derive_for_sum_type(
            type_decl.span,
            type_decl.name,
            trait_kind,
        ));
        return;
    }

    let type_params = collect_generic_params(checker.arena(), type_decl.generics);
    let self_type = if type_params.is_empty() {
        checker.pool_mut().named(type_decl.name)
    } else {
        let type_args: Vec<Idx> = type_params
            .iter()
            .map(|&param| checker.pool_mut().named(param))
            .collect();
        checker.pool_mut().applied(type_decl.name, &type_args)
    };

    // 0b. Reject derives when the required supertrait is missing (E2029)
    if let Some(required) = trait_kind.requires_supertrait() {
        let required_name = checker.interner().intern(required.trait_name());
        let has_derive = type_decl.derives.contains(&required_name);
        if !has_derive {
            // Also check if an explicit impl exists in the trait registry
            let required_idx = checker.pool_mut().named(required_name);
            let has_impl = checker.trait_registry().has_impl(required_idx, self_type);
            if !has_impl {
                checker.push_error(TypeCheckError::cannot_derive_without_supertrait(
                    type_decl.span,
                    type_decl.name,
                    trait_kind,
                    required,
                ));
                return;
            }
        }
    }

    // 1. Get the trait index
    let trait_idx = checker.pool_mut().named(trait_name);

    // 2. Check if this impl already exists (coherence check)
    if checker.trait_registry().has_impl(trait_idx, self_type) {
        // Already have an impl for this trait+type combination
        return;
    }

    // 3. Validate field types implement the derived trait (E2032)
    if !validate_derive_field_constraints(checker, type_decl, trait_name, trait_idx) {
        return;
    }

    // 4. Build method signatures for the derived trait
    let (methods, signature) = build_derived_methods(
        checker,
        trait_kind,
        self_type,
        &type_params,
        trait_name,
        type_decl.span,
    );

    // 5. Create and register the impl entry. A generic `#derive(Eq) type Pair<T>`
    //    is conditional: it implements the trait only when each type argument
    //    satisfies the same trait (derive-implied `impl<T: Eq> Pair<T>: Eq`).
    //    Record that bound per type parameter so the operator-presence gate
    //    rejects an unsatisfied instantiation; a generic conditional impl is
    //    Constrained, a non-generic one stays Concrete.
    let type_param_bounds: Vec<Vec<Name>> = type_params.iter().map(|_| vec![trait_name]).collect();
    debug_assert_eq!(
        type_params.len(),
        type_param_bounds.len(),
        "type_param_bounds must be index-aligned with type_params"
    );
    let specificity = if type_params.is_empty() {
        ImplSpecificity::Concrete
    } else {
        ImplSpecificity::Constrained
    };
    let id = next_derived_impl_id(checker.accepted_derives.len());
    let entry = ImplEntry {
        trait_idx: Some(trait_idx),
        trait_type_args: Vec::new(),
        self_type,
        type_params,
        type_param_bounds,
        methods,
        assoc_types: FxHashMap::default(),
        where_clause: Vec::new(),
        specificity,
        span: type_decl.span,
    };

    // Keep the trait and lowering registries coherent when the ID domain is exhausted.
    checker.trait_registry_mut().register_impl_with_origin(
        entry,
        Some(crate::registry::RegisteredImplOrigin::Derived(id)),
    );
    checker.accepted_derives.push(AcceptedDerivedImpl {
        id,
        owner_name: type_decl.name,
        owner_type: self_type,
        trait_type: trait_idx,
        trait_kind,
        method_name: checker.interner().intern(trait_kind.method_name()),
        signature,
        span: type_decl.span,
    });
}

fn next_derived_impl_id(accepted_count: usize) -> DerivedImplId {
    let Ok(raw_id) = u32::try_from(accepted_count) else {
        panic!("a module cannot contain more than u32::MAX accepted derives");
    };
    DerivedImplId::new(raw_id)
}

/// Validate that all field types implement the derived trait (E2032).
///
/// Returns `true` if validation passes (all fields satisfy the trait or are
/// generic type parameters). Returns `false` if any field definitively fails,
/// after emitting E2032 errors for each failing field.
fn validate_derive_field_constraints(
    checker: &mut ModuleChecker<'_>,
    type_decl: &ori_ir::TypeDecl,
    trait_name: Name,
    trait_idx: Idx,
) -> bool {
    let arena = checker.arena();

    // Collect generic parameter names to skip them during validation.
    // Generic params (e.g., T in Pair<T>) are checked at instantiation.
    let generic_params: FxHashSet<Name> = {
        let params = arena.get_generic_params(type_decl.generics);
        params.iter().map(|p| p.name).collect()
    };

    let self_name = type_decl.name;
    let mut all_valid = true;

    match &type_decl.kind {
        ori_ir::TypeDeclKind::Struct(fields) => {
            for field in fields {
                let field_ty = resolve_parsed_type_simple(checker, &field.ty, arena);
                if !field_type_satisfies_trait(
                    checker,
                    field_ty,
                    trait_name,
                    trait_idx,
                    self_name,
                    &generic_params,
                ) {
                    checker.push_error(TypeCheckError::field_missing_trait_in_derive(
                        field.span,
                        type_decl.name,
                        trait_name,
                        field.name,
                        field_ty,
                    ));
                    all_valid = false;
                }
            }
        }
        ori_ir::TypeDeclKind::Sum(variants) => {
            for variant in variants {
                for field in &variant.fields {
                    let field_ty = resolve_parsed_type_simple(checker, &field.ty, arena);
                    if !field_type_satisfies_trait(
                        checker,
                        field_ty,
                        trait_name,
                        trait_idx,
                        self_name,
                        &generic_params,
                    ) {
                        checker.push_error(TypeCheckError::field_missing_trait_in_derive(
                            field.span,
                            type_decl.name,
                            trait_name,
                            field.name,
                            field_ty,
                        ));
                        all_valid = false;
                    }
                }
            }
        }
        ori_ir::TypeDeclKind::Newtype(underlying) => {
            let underlying_type = resolve_parsed_type_simple(checker, underlying, arena);
            if !field_type_satisfies_trait(
                checker,
                underlying_type,
                trait_name,
                trait_idx,
                self_name,
                &generic_params,
            ) {
                checker.push_error(TypeCheckError::field_missing_trait_in_derive(
                    type_decl.span,
                    type_decl.name,
                    trait_name,
                    type_decl.name,
                    underlying_type,
                ));
                all_valid = false;
            }
        }
    }

    all_valid
}

/// Check if a field type satisfies a trait for derive validation.
///
/// Conservative: returns `true` for generic type parameters (checked at
/// instantiation), self-references, and types where satisfaction can't be
/// determined during registration.
fn field_type_satisfies_trait(
    checker: &ModuleChecker<'_>,
    field_ty: Idx,
    trait_name: Name,
    trait_idx: Idx,
    self_name: Name,
    generic_params: &FxHashSet<Name>,
) -> bool {
    let tag = checker.pool().tag(field_ty);

    // Generic type variables — skip, checked at instantiation
    if matches!(tag, Tag::Var | Tag::BoundVar | Tag::RigidVar | Tag::Infer) {
        return true;
    }

    // Primitives and builtins — use well-known table
    let wk = checker.well_known();
    if wk.type_satisfies_trait(field_ty, trait_name, checker.pool()) {
        return true;
    }

    // Check trait registry for existing impls (covers earlier derives + manual impls)
    if checker.trait_registry().has_impl(trait_idx, field_ty) {
        return true;
    }

    // For Named types: skip self-references and generic parameters
    if tag == Tag::Named {
        let name = checker.pool().named_name(field_ty);
        // Self-reference (e.g., Tree containing Tree fields)
        if name == self_name {
            return true;
        }
        // Generic type parameter (e.g., T in Pair<T>)
        if generic_params.contains(&name) {
            return true;
        }
    }

    // For applied types (generics like List<T>, Option<T>), the trait satisfaction
    // depends on the type arguments. Be conservative and accept.
    if matches!(tag, Tag::Applied) {
        return true;
    }

    false
}

/// Build the method map for a derived trait implementation.
///
/// Each derived trait has a single method with a known signature:
/// - Eq: `eq(self: T, other: T) -> bool`
/// - Clone: `clone(self: T) -> T`
/// - Hashable: `hash(self: T) -> int`
/// - Printable: `to_str(self: T) -> str`
/// - Debug: `debug(self: T) -> str`
/// - Default: `default() -> T`
/// - Comparable: `compare(self: T, other: T) -> Ordering`
pub(super) fn build_derived_methods(
    checker: &mut ModuleChecker<'_>,
    trait_kind: DerivedTrait,
    self_type: Idx,
    type_params: &[Name],
    trait_name: Name,
    span: Span,
) -> (FxHashMap<Name, ImplMethodDef>, FunctionSig) {
    let method_str = trait_kind.method_name();
    let method_name = checker.interner().intern(method_str);

    let self_name = checker.interner().intern("self");
    let other_name = checker.interner().intern("other");
    let (param_names, param_types, return_type) = match trait_kind.shape() {
        DerivedMethodShape::BinaryPredicate => (
            vec![self_name, other_name],
            vec![self_type, self_type],
            Idx::BOOL,
        ),
        DerivedMethodShape::UnaryIdentity => (vec![self_name], vec![self_type], self_type),
        DerivedMethodShape::UnaryToInt => (vec![self_name], vec![self_type], Idx::INT),
        DerivedMethodShape::UnaryToStr => (vec![self_name], vec![self_type], Idx::STR),
        DerivedMethodShape::Nullary => (Vec::new(), Vec::new(), self_type),
        DerivedMethodShape::BinaryToOrdering => (
            vec![self_name, other_name],
            vec![self_type, self_type],
            Idx::ORDERING,
        ),
    };
    let mut signature = FunctionSig::synthetic(method_name, param_names, param_types, return_type);
    signature.type_params = type_params.to_vec();
    signature.type_param_bounds = type_params.iter().map(|_| vec![trait_name]).collect();
    signature.generic_param_mapping = vec![None; type_params.len()];
    signature.populate_hashes(checker.pool());
    let signature_type = signature.to_function_type(checker.pool_mut());

    let has_self = trait_kind.shape().has_self();

    let mut methods = FxHashMap::default();
    methods.insert(
        method_name,
        ImplMethodDef {
            name: method_name,
            signature: signature_type,
            has_self,
            body: ExprId::INVALID,
            // Derived methods have no method-level binders by construction
            // — the deriver synthesizes monomorphic-shape methods.
            scheme_var_ids: Vec::new(),
            generic_param_metadata: Vec::new(),
            where_clause_metadata: Vec::new(),
            fixed_list_capacity_constraints: Vec::new(),
            // Derived methods have no defaulted params → strict arity.
            optional_param_count: 0,
            span,
        },
    );
    (methods, signature)
}
