//! Drop function IR generation for ARC reference counting.
//!
//! Generates specialized LLVM IR drop functions from [`ori_arc::DropInfo`]
//! descriptors. Each drop function is `extern "C" fn(*mut u8)` — called by
//! `ori_rc_dec` when a refcount reaches zero. The function decrements RC'd
//! children, then frees the allocation via `ori_rc_free`.
//!
//! # Drop function variants
//!
//! | `DropKind` | IR pattern |
//! |----------------|--------------------------------------------------|
//! | `Trivial` | `ori_rc_free(ptr, size, align)` + ret |
//! | `Fields` | GEP+load+`ori_rc_dec` per RC'd field, then free |
//! | `ClosureEnv` | Same as Fields (different naming) |
//! | `Enum` | Switch on tag → per-variant field drops, then free|
//! | `Collection` | Loop: dec each element, free buffer, then free |
//! | `Map` | Loop: dec keys/values, free buffer, then free |
//!
//! # Cycle safety
//!
//! Drop functions are cached in `ArcIrEmitter::drop_fn_cache` and the
//! `FunctionId` is inserted **before** generating the body. This handles
//! recursive types (e.g., linked lists) where the drop function references
//! itself for child decrements.

use ori_arc::{DropInfo, DropKind};
use ori_types::Idx;

use crate::codegen::value_id::{FunctionId, ValueId};

use super::context::is_boxed_enum_field;
use super::ArcIrEmitter;

/// Generate an LLVM drop function for the given type.
///
/// Declares a `void (ptr)` function with `nounwind` + `cold` attributes,
/// caches the `FunctionId` immediately (cycle safety), then generates the
/// body based on `DropKind`.
///
/// Naming is an LLVM projection owned by [`crate::drop_glue_symbol`].
pub(super) fn generate_drop_fn<'a, 'scx: 'ctx, 'ctx, 'tcx>(
    emitter: &mut ArcIrEmitter<'a, 'scx, 'ctx, 'tcx>,
    ty: Idx,
    drop_info: &DropInfo,
) -> FunctionId {
    let func_name = crate::drop_glue_symbol(ty);

    // Get-or-declare: reuse an existing function from a previous emitter instance
    // to avoid duplicate definitions (LLVM would auto-rename with `.1`, `.2`, etc.)
    let ptr_ty = emitter.builder.ptr_type();
    let func_id = emitter
        .builder
        .get_or_declare_void_function(&func_name, &[ptr_ty]);

    // If this function already has a body (generated by a previous emitter instance),
    // just cache it and return — no need to regenerate identical drop logic.
    if emitter.builder.function_has_body(func_id) {
        emitter.drop_fn_cache.insert(ty, func_id);
        return func_id;
    }

    emitter.builder.set_module_local(func_id);
    // A may-unwind drop fn (its drop tree reaches a user `@drop` that may raise
    // a foreign Ori exception) MUST NOT be `nounwind` — it threads the
    // exception out via a cleanup landing pad that runs the field walk and
    // free before resuming. SEH drop-function cleanup pads are not emitted;
    // other drop functions remain `nounwind`.
    let drop_unwinds = emitter.drop_may_unwind(ty)
        && emitter.builder.eh_model() == crate::codegen::eh_model::EhModel::Itanium;
    if drop_unwinds {
        let personality = emitter.builder.runtime_fn("ori_eh_personality");
        emitter.builder.set_personality(func_id, personality);
    } else {
        emitter.builder.add_nounwind_attribute(func_id);
    }
    emitter.builder.add_cold_attribute(func_id);
    emitter.builder.add_uwtable_attribute(func_id);
    // noundef on data pointer param — Ori never passes poison pointers.
    emitter.builder.add_noundef_param_attribute(func_id, 0);

    // Cache before body generation (cycle safety for recursive types)
    emitter.drop_fn_cache.insert(ty, func_id);

    // Create entry block and position builder.
    // Set BOTH builder.current_function AND emitter.current_function so that
    // SSO-check blocks (created by inc_value_rc/dec_value_rc) are appended to
    // the drop function, not the caller's function.
    let entry = emitter.builder.append_block(func_id, "entry");
    emitter.builder.position_at_end(entry);
    emitter.builder.set_current_function(func_id);
    emitter.current_function = func_id;

    // Data pointer parameter
    let data_ptr = emitter.builder.get_param(func_id, 0);

    // Generate body based on drop kind
    match &drop_info.kind {
        DropKind::Trivial => {
            emitter.emit_drop_rc_free(data_ptr, ty);
            emitter.builder.ret_void();
        }

        DropKind::Fields { fields, user_drop } => {
            emitter.emit_drop_fields(data_ptr, ty, fields, *user_drop);
        }

        DropKind::ClosureEnv(fields) => {
            // Closure environments cannot carry user @drop (closures
            // are not nominal types). Pass None.
            emitter.emit_drop_fields(data_ptr, ty, fields, None);
        }

        DropKind::Enum {
            variants,
            user_drop,
        } => {
            emitter.emit_drop_enum(func_id, data_ptr, ty, variants, *user_drop);
        }

        DropKind::Collection { element_type } => {
            emitter.emit_drop_collection(func_id, data_ptr, ty, *element_type);
        }

        DropKind::Map {
            key_type,
            value_type,
            dec_keys,
            dec_values,
        } => {
            emitter.emit_drop_map(
                func_id,
                data_ptr,
                ty,
                *key_type,
                *value_type,
                *dec_keys,
                *dec_values,
            );
        }
    }

    // Function-level LLVM IR verification for generated drop functions.
    if emitter.verify_arc {
        let fn_val = emitter.builder.get_function_value(func_id);
        if !fn_val.verify(true) {
            tracing::error!(
                name = func_name,
                "LLVM IR verification failed (generate_drop_fn)"
            );
            emitter.builder.record_codegen_error();
        }
    }

    func_id
}

// All body generators live in an impl block so they inherit the correct
// lifetime bounds from ArcIrEmitter's declaration (`'scx: 'ctx`).
impl<'scx: 'ctx, 'ctx> ArcIrEmitter<'_, 'scx, 'ctx, '_> {
    // Body generators

    /// Emit drop body for struct/tuple/closure-env with specific RC'd fields.
    ///
    /// When the type implements `Drop` (resolved via [`Self::user_drop_method`]
    /// on the canonical method map), codegen materializes the AUGMENT body per
    /// `drop-trait-proposal.md` Execution Timing section: run the user `@drop`
    /// FIRST (sees fields valid), then walk owned fields in REVERSE declaration
    /// order (LIFO), then free. Without a user `@drop`, the plain field walk +
    /// free is emitted.
    ///
    /// When the type's own `@drop` may unwind (Itanium), the user `@drop` is
    /// emitted as an `invoke`: on normal return the reverse field walk + free
    /// run in the continuation block; on a `@drop` panic the cleanup landing
    /// pad re-runs the field walk + free (so owned fields are freed — no leak),
    /// then `resume`s the foreign exception to the caller. Otherwise the user
    /// `@drop` is a plain `call` (a panic aborts via the `call_drop_fn` runtime
    /// guard on the non-unwinding path).
    fn emit_drop_fields(
        &mut self,
        data_ptr: ValueId,
        ty: Idx,
        fields: &[(u32, Idx)],
        _user_drop: Option<ori_registry::burden::FnSym>,
    ) {
        let reversed: Vec<(u32, Idx)> = super::emitter_utils::field_rc_walk_order(
            fields,
            super::emitter_utils::FieldRcWalkOrder::Teardown,
        );

        // Recoverable path: the type's OWN `@drop` may unwind (a panicking
        // user `@drop`). A field-only may-unwind (no own `@drop`) takes the
        // plain field-walk path — the per-field drops propagate through this
        // frame's personality without a local landing pad.
        let own_drop_unwinds = self.user_drop_method(ty).is_some()
            && self.drop_may_unwind(ty)
            && self.builder.eh_model() == crate::codegen::eh_model::EhModel::Itanium;

        if own_drop_unwinds {
            let cont_bb = self
                .builder
                .append_block(self.current_function, "udrop.cont");
            let cleanup_bb = self
                .builder
                .append_block(self.current_function, "udrop.cleanup");
            // invoke @drop → cont_bb (normal) / cleanup_bb (unwind)
            if self.invoke_user_drop_via_pointer(ty, data_ptr, cont_bb, cleanup_bb) {
                // Normal continuation: field walk + free + ret.
                self.builder.position_at_end(cont_bb);
                self.emit_drop_field_loop(data_ptr, ty, &reversed, None, "f");
                self.emit_drop_rc_free(data_ptr, ty);
                self.builder.ret_void();

                // Cleanup pad: field walk + free still run (no leak), then
                // re-raise the foreign exception to the caller's cleanup pad.
                self.builder.position_at_end(cleanup_bb);
                let personality = self.builder.runtime_fn("ori_eh_personality");
                let lp = self.builder.landingpad(personality, true, "udrop.lp");
                let enter = self.builder.runtime_fn("ori_drop_cleanup_enter");
                self.builder.call(enter, &[], "");
                self.emit_drop_field_loop(data_ptr, ty, &reversed, None, "f.cl");
                self.emit_drop_rc_free(data_ptr, ty);
                let exit = self.builder.runtime_fn("ori_drop_cleanup_exit");
                self.builder.call(exit, &[], "");
                self.builder.resume(lp);
                return;
            }
            // No user `@drop` resolved after all — fall through to plain path.
        }

        // Plain path: user `@drop` (if any) as a plain call, then field walk.
        self.emit_user_drop_via_pointer(ty, data_ptr);
        self.emit_drop_field_loop(data_ptr, ty, &reversed, None, "f");
        self.emit_drop_rc_free(data_ptr, ty);
        self.builder.ret_void();
    }

    /// SSOT for "iterate struct/tuple-shaped RC'd fields, optionally skipping
    /// indices, and emit `GEP+load+emit_drop_rc_dec` per included field."
    ///
    /// Exit invariant: NO `emit_drop_rc_free`, NO `ret_void` — callers own
    /// finalization. Used by:
    ///   - [`Self::emit_drop_fields`] (drop-fn body; caller adds free+ret).
    ///   - `BurdenDecField` arm at `instr_dispatch.rs` (single-field
    ///     cleanup before `Set` mutation; mid-block, no finalization).
    ///   - `BurdenDecPartial` arm at `instr_dispatch.rs` (partial-move
    ///     cleanup with `skip` containing moved-out indices; mid-block,
    ///     no finalization).
    ///
    /// `remap_struct_field` is consulted per-field so memory-order matches
    /// `ReprPlan`'s reordering (closure envs are exempt — their tag is
    /// neither Struct nor Tuple, so `remap_struct_field` returns the
    /// declaration index unchanged).
    pub(super) fn emit_drop_field_loop(
        &mut self,
        data_ptr: ValueId,
        ty: Idx,
        fields: &[(u32, Idx)],
        skip: Option<&[u32]>,
        name_prefix: &str,
    ) {
        let struct_llvm_ty = self.resolve_type(ty);

        for &(field_index, field_type) in fields {
            if let Some(skipped) = skip {
                if skipped.contains(&field_index) {
                    continue;
                }
            }
            let mem_index = self.remap_struct_field(ty, field_index);
            let field_ptr = self.builder.struct_gep(
                struct_llvm_ty,
                data_ptr,
                mem_index,
                &format!("{name_prefix}.{field_index}.ptr"),
            );
            if is_boxed_enum_field(self.pool, ty, field_type) {
                // Recursive back-edge: the slot holds an RC pointer to the
                // heap-boxed child, not the inline aggregate. Load the box
                // pointer and dec through the field type's drop fn.
                let ptr_ty = self.builder.ptr_type();
                let rc_ptr = self.builder.load(
                    ptr_ty,
                    field_ptr,
                    &format!("{name_prefix}.{field_index}.rc"),
                );
                let drop_fn = self.get_or_generate_drop_fn(field_type);
                self.emit_drop_rc_dec_with_fn(rc_ptr, drop_fn);
            } else {
                let field_llvm_ty = self.resolve_type(field_type);
                let field_val = self.builder.load(
                    field_llvm_ty,
                    field_ptr,
                    &format!("{name_prefix}.{field_index}"),
                );
                // Inline struct/enum field with a user `@drop` (e.g. a closure-
                // env capture, or a not-yet-walked sibling in a cleanup pad):
                // run its `@drop` before the field walk. Plain (non-invoking)
                // call — this loop is used on the closure-env drop path and the
                // cleanup-pad tail walk, neither of which threads an invoke
                // edge per field.
                self.emit_user_drop_for_inline_value(field_type, field_val);
                self.emit_drop_rc_dec(field_val, field_type);
            }
        }
    }
}
