//! Drop function IR generation for ARC reference counting.
//!
//! Generates specialized LLVM IR drop functions from [`ori_arc::DropInfo`]
//! descriptors. Each drop function is `extern "C" fn(*mut u8)` — called by
//! `ori_rc_dec` when a refcount reaches zero. The function decrements RC'd
//! children, then frees the allocation via `ori_rc_free`.
//!
//! # Drop function variants
//!
//! | `DropKind`     | IR pattern                                       |
//! |----------------|--------------------------------------------------|
//! | `Trivial`      | `ori_rc_free(ptr, size, align)` + ret             |
//! | `Fields`       | GEP+load+`ori_rc_dec` per RC'd field, then free  |
//! | `ClosureEnv`   | Same as Fields (different naming)                 |
//! | `Enum`         | Switch on tag → per-variant field drops, then free|
//! | `Collection`   | Loop: dec each element, free buffer, then free    |
//! | `Map`          | Loop: dec keys/values, free buffer, then free     |
//!
//! # Cycle safety
//!
//! Drop functions are cached in `ArcIrEmitter::drop_fn_cache` and the
//! `FunctionId` is inserted **before** generating the body. This handles
//! recursive types (e.g., linked lists) where the drop function references
//! itself for child decrements.

use ori_arc::{DropInfo, DropKind};
use ori_ir::{CLOSURE_FIELD_ENV, FIELD_CAP, FIELD_DATA, FIELD_LEN};
use ori_types::Idx;

use super::context::{is_boxed_enum_field, tagged_union_has_boxed_inner};
use super::ArcIrEmitter;
use crate::codegen::value_id::{FunctionId, ValueId};

/// Generate an LLVM drop function for the given type.
///
/// Declares a `void (ptr)` function with `nounwind` + `cold` attributes,
/// caches the `FunctionId` immediately (cycle safety), then generates the
/// body based on `DropKind`.
///
/// Naming: `_ori_drop$<idx_raw>` — unique per type pool index.
pub(super) fn generate_drop_fn<'a, 'scx: 'ctx, 'ctx, 'tcx>(
    emitter: &mut ArcIrEmitter<'a, 'scx, 'ctx, 'tcx>,
    ty: Idx,
    drop_info: &DropInfo,
) -> FunctionId {
    let func_name = format!("_ori_drop${}", ty.raw());

    // Get-or-declare: reuse an existing function from a previous emitter instance
    // to avoid duplicate definitions (LLVM would auto-rename with `.1`, `.2`, etc.)
    let ptr_ty = emitter.builder.ptr_type();
    let func_id = emitter
        .builder
        .get_or_declare_void_function(&func_name, &[ptr_ty]);

    // If this function already has a body (generated by a previous emitter instance),
    // just cache it and return — no need to regenerate identical drop logic.
    if emitter.builder.function_has_body(func_id) {
        emitter.drop_fn_cache.insert(ty, func_id);
        return func_id;
    }

    emitter.builder.set_ccc(func_id);
    emitter.builder.add_nounwind_attribute(func_id);
    emitter.builder.add_cold_attribute(func_id);
    emitter.builder.add_uwtable_attribute(func_id);
    // noundef on data pointer param — Ori never passes poison pointers.
    emitter.builder.add_noundef_param_attribute(func_id, 0);

    // Cache before body generation (cycle safety for recursive types)
    emitter.drop_fn_cache.insert(ty, func_id);

    // Create entry block and position builder.
    // Set BOTH builder.current_function AND emitter.current_function so that
    // SSO-check blocks (created by inc_value_rc/dec_value_rc) are appended to
    // the drop function, not the caller's function.
    let entry = emitter.builder.append_block(func_id, "entry");
    emitter.builder.position_at_end(entry);
    emitter.builder.set_current_function(func_id);
    emitter.current_function = func_id;

    // Data pointer parameter
    let data_ptr = emitter.builder.get_param(func_id, 0);

    // Generate body based on drop kind
    match &drop_info.kind {
        DropKind::Trivial => {
            emitter.emit_drop_rc_free(data_ptr, ty);
            emitter.builder.ret_void();
        }

        DropKind::Fields { fields, user_drop } => {
            emitter.emit_drop_fields(data_ptr, ty, fields, *user_drop);
        }

        DropKind::ClosureEnv(fields) => {
            // Closure environments cannot carry user @drop (closures
            // are not nominal types). Pass None.
            emitter.emit_drop_fields(data_ptr, ty, fields, None);
        }

        DropKind::Enum {
            variants,
            user_drop,
        } => {
            emitter.emit_drop_enum(func_id, data_ptr, ty, variants, *user_drop);
        }

        DropKind::Collection { element_type } => {
            emitter.emit_drop_collection(func_id, data_ptr, ty, *element_type);
        }

        DropKind::Map {
            key_type,
            value_type,
            dec_keys,
            dec_values,
        } => {
            emitter.emit_drop_map(
                func_id,
                data_ptr,
                ty,
                *key_type,
                *value_type,
                *dec_keys,
                *dec_values,
            );
        }
    }

    // Function-level LLVM IR verification for generated drop functions.
    if emitter.verify_arc {
        let fn_val = emitter.builder.get_function_value(func_id);
        if !fn_val.verify(true) {
            tracing::error!(
                name = func_name,
                "LLVM IR verification failed (generate_drop_fn)"
            );
            emitter.builder.record_codegen_error();
        }
    }

    func_id
}

// All body generators live in an impl block so they inherit the correct
// lifetime bounds from ArcIrEmitter's declaration (`'scx: 'ctx`).
impl<'scx: 'ctx, 'ctx> ArcIrEmitter<'_, 'scx, 'ctx, '_> {
    // Body generators

    /// Emit drop body for struct/tuple/closure-env with specific RC'd fields.
    ///
    /// `user_drop` carries the user `@drop` `FnSym` when the type implements
    /// the `Drop` trait — codegen materializes the AUGMENT body per
    /// `drop-trait-proposal.md` Execution Timing section:
    ///   1. Invoke `user_drop(data_ptr)` FIRST (user @drop sees fields
    ///      valid; compiler has not yet walked them).
    ///   2. Walk owned fields in REVERSE declaration order (matches the
    ///      proposal's LIFO rule).
    ///   3. Free the allocation via `emit_drop_rc_free`.
    ///
    /// Without `user_drop`, the function emits the plain field walk +
    /// free.
    ///
    /// The `user_drop` call uses a plain `call`, not an `invoke` +
    /// landing-pad wrapper. A panic in the @drop body therefore aborts via
    /// the `call_drop_fn` runtime guard (per `ori_rt::rc::call_drop_fn`),
    /// which exits with `SIGABRT_EXIT_CODE` — sound, but stricter than the
    /// "first panic recoverable" stance: the field walk does not run on the
    /// unwind path. The AUGMENT body shape is in place; landing-pad wiring
    /// is unimplemented.
    fn emit_drop_fields(
        &mut self,
        data_ptr: ValueId,
        ty: Idx,
        fields: &[(u32, Idx)],
        user_drop: Option<ori_registry::burden::FnSym>,
    ) {
        if let Some(fn_sym) = user_drop {
            self.emit_user_drop_call(data_ptr, ty, fn_sym);
        }
        // Field walk: emit in REVERSE declaration order per
        // `drop-trait-proposal.md §85`. `emit_drop_field_loop` iterates
        // the slice in caller-supplied order, so we reverse the fields
        // here before passing in.
        let reversed: Vec<(u32, Idx)> = fields.iter().rev().copied().collect();
        self.emit_drop_field_loop(data_ptr, ty, &reversed, None, "f");
        self.emit_drop_rc_free(data_ptr, ty);
        self.builder.ret_void();
    }

    /// Emit a plain `call` to the user @drop method FOR the AUGMENT body.
    ///
    /// The user @drop method is a normal impl method compiled via
    /// `compile_impls`; its mangled name follows the type-qualified scheme
    /// (`_ori_<Type>$drop`). The
    /// `FnSym` is a sync token minted by `mint_compiled_drop_fn_sym` at
    /// `register_impl` time — codegen looks up the actual LLVM function
    /// via `get_or_declare_function` on the canonical mangled name.
    ///
    /// `_fn_sym` is currently unused by the call-site lookup — the
    /// mangled name is derived from the type `Idx` via `ty.raw()`. The
    /// `FnSym` parameter is kept on the API surface so the caller-side
    /// invariant (`user @drop is wired through DropKind.user_drop`)
    /// remains explicit; future wiring can use the `FnSym` to disambiguate
    /// when one type carries multiple drop variants.
    fn emit_user_drop_call(
        &mut self,
        data_ptr: ValueId,
        ty: Idx,
        _fn_sym: ori_registry::burden::FnSym,
    ) {
        // Drop method mangling follows the type-qualified mangling scheme;
        // in the absence of a direct name-resolution API here, the call
        // uses the structured `_ori_user_drop$<idx>` route. This is the
        // AUGMENT body shape; full AOT user-@drop integration is
        // unimplemented.
        let func_name = format!("_ori_user_drop${}", ty.raw());
        let ptr_ty = self.builder.ptr_type();
        let user_drop_fn = self
            .builder
            .get_or_declare_void_function(&func_name, &[ptr_ty]);
        // Per `drop-trait-proposal.md §Drop and panic`, drop bodies are
        // declared synchronous and may not unwind through `nounwind`
        // boundaries (the runtime catches panics in `call_drop_fn`).
        // Emit a plain call; future work routes through `invoke` +
        // landing pad for first-panic recovery semantics.
        self.builder.call(user_drop_fn, &[data_ptr], "");
    }

    /// SSOT for "iterate struct/tuple-shaped RC'd fields, optionally skipping
    /// indices, and emit `GEP+load+emit_drop_rc_dec` per included field."
    ///
    /// Exit invariant: NO `emit_drop_rc_free`, NO `ret_void` — callers own
    /// finalization. Used by:
    ///   - [`Self::emit_drop_fields`] (drop-fn body; caller adds free+ret).
    ///   - `BurdenDecField` arm at `instr_dispatch.rs` (single-field
    ///     cleanup before `Set` mutation; mid-block, no finalization).
    ///   - `BurdenDecPartial` arm at `instr_dispatch.rs` (partial-move
    ///     cleanup with `skip` containing moved-out indices; mid-block,
    ///     no finalization).
    ///
    /// `remap_struct_field` is consulted per-field so memory-order matches
    /// `ReprPlan`'s reordering (closure envs are exempt — their tag is
    /// neither Struct nor Tuple, so `remap_struct_field` returns the
    /// declaration index unchanged).
    pub(super) fn emit_drop_field_loop(
        &mut self,
        data_ptr: ValueId,
        ty: Idx,
        fields: &[(u32, Idx)],
        skip: Option<&[u32]>,
        name_prefix: &str,
    ) {
        let struct_llvm_ty = self.resolve_type(ty);

        for &(field_index, field_type) in fields {
            if let Some(skipped) = skip {
                if skipped.contains(&field_index) {
                    continue;
                }
            }
            let mem_index = self.remap_struct_field(ty, field_index);
            let field_ptr = self.builder.struct_gep(
                struct_llvm_ty,
                data_ptr,
                mem_index,
                &format!("{name_prefix}.{field_index}.ptr"),
            );
            if is_boxed_enum_field(self.pool, ty, field_type) {
                // Recursive back-edge: the slot holds an RC pointer to the
                // heap-boxed child, not the inline aggregate. Load the box
                // pointer and dec through the field type's drop fn.
                let ptr_ty = self.builder.ptr_type();
                let rc_ptr = self.builder.load(
                    ptr_ty,
                    field_ptr,
                    &format!("{name_prefix}.{field_index}.rc"),
                );
                let drop_fn = self.get_or_generate_drop_fn(field_type);
                self.emit_drop_rc_dec_with_fn(rc_ptr, drop_fn);
            } else {
                let field_llvm_ty = self.resolve_type(field_type);
                let field_val = self.builder.load(
                    field_llvm_ty,
                    field_ptr,
                    &format!("{name_prefix}.{field_index}"),
                );
                self.emit_drop_rc_dec(field_val, field_type);
            }
        }
    }

    /// Emit drop body for a collection type ([T], set[T]).
    fn emit_drop_collection(
        &mut self,
        func_id: FunctionId,
        data_ptr: ValueId,
        ty: Idx,
        element_type: Idx,
    ) {
        let list_llvm_ty = self.resolve_type(ty);
        let i64_ty = self.builder.i64_type();
        let ptr_ty = self.builder.ptr_type();

        // Load len (field 0), cap (field 1), data pointer (field 2)
        let len_ptr = self
            .builder
            .struct_gep(list_llvm_ty, data_ptr, FIELD_LEN, "len.ptr");
        let len = self.builder.load(i64_ty, len_ptr, "len");

        let cap_ptr = self
            .builder
            .struct_gep(list_llvm_ty, data_ptr, FIELD_CAP, "cap.ptr");
        let cap = self.builder.load(i64_ty, cap_ptr, "cap");

        let data_field_ptr =
            self.builder
                .struct_gep(list_llvm_ty, data_ptr, FIELD_DATA, "data.field.ptr");
        let elem_data = self.builder.load(ptr_ty, data_field_ptr, "elem_data");

        // Get element drop function (may recursively generate)
        let elem_drop_fn = self.get_or_generate_drop_fn(element_type);

        // Emit dec loop
        self.emit_drop_element_loop(func_id, elem_data, len, element_type, elem_drop_fn, "elem");

        // Free element buffer + collection struct
        // Pass collection type for narrowed element size.
        let resolved_ty = self.pool.resolve_fully(ty);
        self.emit_drop_list_free_data(elem_data, cap, element_type, Some(resolved_ty));
        self.emit_drop_rc_free(data_ptr, ty);
        self.builder.ret_void();
    }

    /// Emit drop body for a map type ({K: V}).
    #[expect(
        clippy::too_many_arguments,
        reason = "mirrors DropKind::Map fields; grouping would add indirection"
    )]
    fn emit_drop_map(
        &mut self,
        func_id: FunctionId,
        data_ptr: ValueId,
        ty: Idx,
        key_type: Idx,
        value_type: Idx,
        dec_keys: bool,
        dec_values: bool,
    ) {
        let map_llvm_ty = self.resolve_type(ty);
        let i64_ty = self.builder.i64_type();
        let ptr_ty = self.builder.ptr_type();

        // Map layout: { i64 len, i64 cap, ptr keys, ptr values }
        let len_ptr = self
            .builder
            .struct_gep(map_llvm_ty, data_ptr, FIELD_LEN, "len.ptr");
        let len = self.builder.load(i64_ty, len_ptr, "len");

        if dec_keys {
            let keys_ptr = self
                .builder
                .struct_gep(map_llvm_ty, data_ptr, 2, "keys.field.ptr");
            let keys_data = self.builder.load(ptr_ty, keys_ptr, "keys_data");
            let key_drop_fn = self.get_or_generate_drop_fn(key_type);
            self.emit_drop_element_loop(func_id, keys_data, len, key_type, key_drop_fn, "key");
        }

        if dec_values {
            let vals_ptr = self
                .builder
                .struct_gep(map_llvm_ty, data_ptr, 3, "vals.field.ptr");
            let vals_data = self.builder.load(ptr_ty, vals_ptr, "vals_data");
            let val_drop_fn = self.get_or_generate_drop_fn(value_type);
            self.emit_drop_element_loop(func_id, vals_data, len, value_type, val_drop_fn, "val");
        }

        self.emit_drop_rc_free(data_ptr, ty);
        self.builder.ret_void();
    }

    /// Emit a loop that decrements RC for each element in an array.
    ///
    /// Shared between collection and map drop.
    fn emit_drop_element_loop(
        &mut self,
        func_id: FunctionId,
        array_ptr: ValueId,
        len: ValueId,
        element_type: Idx,
        elem_drop_fn: ValueId,
        prefix: &str,
    ) {
        let i64_ty = self.builder.i64_type();
        let elem_llvm_ty = self.resolve_type(element_type);

        let entry_block = self.builder.current_block().expect("current block");
        let loop_header = self
            .builder
            .append_block(func_id, &format!("{prefix}.loop.hdr"));
        let loop_body = self
            .builder
            .append_block(func_id, &format!("{prefix}.loop.body"));
        let loop_done = self
            .builder
            .append_block(func_id, &format!("{prefix}.loop.done"));

        let zero = self.builder.const_i64(0);
        let one = self.builder.const_i64(1);

        // entry → loop.header
        self.builder.br(loop_header);

        // loop.header: phi + cmp + branch
        self.builder.position_at_end(loop_header);
        let i_phi = self.builder.phi(i64_ty, &format!("{prefix}.i"));
        let done = self.builder.icmp_sge(i_phi, len, &format!("{prefix}.done"));
        self.builder.cond_br(done, loop_done, loop_body);

        // loop.body: load element, extract data ptr(s), dec, increment, loop back
        self.builder.position_at_end(loop_body);
        let elem_ptr =
            self.builder
                .gep(elem_llvm_ty, array_ptr, &[i_phi], &format!("{prefix}.ptr"));
        let elem_val = self
            .builder
            .load(elem_llvm_ty, elem_ptr, &format!("{prefix}.val"));
        let data_ptrs = self.extract_rc_data_ptrs(elem_val, element_type);
        for ptr in data_ptrs {
            self.emit_drop_rc_dec_with_fn(ptr, elem_drop_fn);
        }
        let i_next = self.builder.add(i_phi, one, &format!("{prefix}.i.next"));
        self.builder.br(loop_header);

        // Patch phi: entry → 0, loop.body → i.next
        self.builder
            .add_phi_incoming(i_phi, &[(zero, entry_block), (i_next, loop_body)]);

        // Position at loop.done for caller to continue
        self.builder.position_at_end(loop_done);
    }

    // Runtime call helpers

    /// Emit `ori_rc_dec` for a child field value.
    ///
    /// Extracts embedded data pointer(s) from aggregate types (Str, List, etc.)
    /// before calling `ori_rc_dec`, since the runtime expects raw pointers.
    ///
    /// Closures (`Tag::Function`) are special: the drop function is stored
    /// dynamically in the env header (field 0 of the heap allocation), not
    /// generated statically. Uses the same pattern as `emit_rc_dec_closure`.
    pub(super) fn emit_drop_rc_dec(&mut self, val: ValueId, field_type: Idx) {
        let resolved = self.pool.resolve_fully(field_type);
        let tag = self.pool.tag(resolved);

        // Closures need dynamic drop fn from env header, not a static one.
        if tag == ori_types::Tag::Function {
            self.emit_closure_field_rc_dec(val);
            return;
        }

        // Tagged unions (Option/Result/Enum) carrying a BOXED RECURSIVE inner
        // MUST be dropped tag-aware: the inactive variant's payload slot holds
        // the niche/tag, not a valid pointer. The flat extract_rc_data_ptrs
        // path would unconditionally dec that slot — a crash when the inner is
        // a boxed recursive pointer (the None tag `0x1` is not null, so
        // ori_rc_dec faults). dec_value_rc switches on the discriminant and
        // decs only the live variant. Non-recursive tagged unions keep the
        // flat path (their data ptrs are inner heap pointers that ori_rc_dec
        // null-checks safely).
        if matches!(
            tag,
            ori_types::Tag::Option | ori_types::Tag::Result | ori_types::Tag::Enum
        ) && tagged_union_has_boxed_inner(self.pool, resolved)
        {
            self.dec_value_rc(val, field_type);
            return;
        }

        let data_ptrs = self.extract_rc_data_ptrs(val, field_type);
        if data_ptrs.is_empty() {
            return;
        }
        let drop_fn = self.get_or_generate_drop_fn(field_type);
        for ptr in data_ptrs {
            self.emit_drop_rc_dec_with_fn(ptr, drop_fn);
        }
    }

    /// Emit RC dec for a closure field value `{ fn_ptr, env_ptr }`.
    ///
    /// Extracts `env_ptr` (field 1), null-checks it, loads the dynamic
    /// drop function from `env_ptr[0]`, and calls `ori_rc_dec(env_ptr, drop_fn)`.
    fn emit_closure_field_rc_dec(&mut self, closure_val: ValueId) {
        let Some(env_ptr) = self
            .builder
            .extract_value(closure_val, CLOSURE_FIELD_ENV, "clos.env")
        else {
            return;
        };

        // Non-capturing closures have a constant null env — skip entirely.
        if self.builder.is_const_null_ptr(env_ptr) {
            return;
        }

        let is_null = self.builder.is_null_ptr(env_ptr, "clos.null");
        let do_dec = self.builder.append_block(self.current_function, "clos.dec");
        let skip = self
            .builder
            .append_block(self.current_function, "clos.skip");
        self.builder.cond_br(is_null, skip, do_dec);

        self.builder.position_at_end(do_dec);
        let ptr_ty = self.builder.ptr_type();
        let drop_fn = self.builder.load(ptr_ty, env_ptr, "clos.drop_fn");
        let rc_dec_id = self.builder.runtime_fn("ori_rc_dec");
        self.emit_rt_call(rc_dec_id, &[env_ptr, drop_fn], "");
        self.builder.br(skip);

        self.builder.position_at_end(skip);
    }

    /// Emit `ori_rc_dec(val, drop_fn_ptr)` with a pre-computed drop function.
    pub(super) fn emit_drop_rc_dec_with_fn(&mut self, val: ValueId, drop_fn_ptr: ValueId) {
        let func_id = self.builder.runtime_fn("ori_rc_dec");
        self.builder.call(func_id, &[val, drop_fn_ptr], "");
    }

    /// Emit `ori_rc_free(data_ptr, size, align)` to deallocate an RC object.
    pub(super) fn emit_drop_rc_free(&mut self, data_ptr: ValueId, ty: Idx) {
        let size = self.element_store_size(ty);
        let align = u64::from(self.type_info.get(ty).alignment());

        let size_val = self.builder.const_i64(size as i64);
        let align_val = self.builder.const_i64(align as i64);

        let func_id = self.builder.runtime_fn("ori_rc_free");
        self.builder
            .call(func_id, &[data_ptr, size_val, align_val], "");
    }

    /// Emit `ori_list_free_data(data, cap, elem_size)` to free a collection buffer.
    ///
    /// `collection_ty` is the resolved collection type (e.g., `[int]`), used
    /// for narrowed element size lookup. Falls back to canonical
    /// size when `None`.
    fn emit_drop_list_free_data(
        &mut self,
        data: ValueId,
        cap: ValueId,
        element_type: Idx,
        collection_ty: Option<Idx>,
    ) {
        let elem_size = if let Some(coll_ty) = collection_ty {
            self.collection_elem_size(coll_ty, element_type)
        } else {
            self.element_store_size(element_type)
        };
        let elem_size_val = self.builder.const_i64(elem_size as i64);

        let func_id = self.builder.runtime_fn("ori_list_free_data");
        self.builder.call(func_id, &[data, cap, elem_size_val], "");
    }
}
