//! ID and range newtypes for the canonical IR.
//!
//! These types provide type-safe indices into [`CanArena`](super::CanArena)
//! storage, preventing accidental cross-use with `ExprId`/`ExprRange` from
//! the parse-level AST.

use std::fmt;
use std::hash::{Hash, Hasher};

use crate::macros::define_range;

/// Index into a [`CanArena`](super::CanArena). Distinct from
/// [`ExprId`](crate::ExprId) — these reference canonical expressions
/// in a separate index space.
///
/// # Salsa Compatibility
/// Implements `Copy`, `Clone`, `Eq`, `PartialEq`, `Hash`, `Debug`.
#[derive(Copy, Clone, Eq, PartialEq)]
#[repr(transparent)]
pub struct CanId(u32);

impl CanId {
    /// Sentinel value indicating "no expression" (analogous to `ExprId::INVALID`).
    /// Used for optional child expressions (e.g., no else branch, no guard).
    pub const INVALID: CanId = CanId(u32::MAX);

    /// Create a new `CanId` from a raw index.
    #[inline]
    pub const fn new(index: u32) -> Self {
        Self(index)
    }

    /// Get the raw index into the arena.
    #[inline]
    pub const fn index(self) -> usize {
        self.0 as usize
    }

    /// Get the raw `u32` value.
    #[inline]
    pub const fn raw(self) -> u32 {
        self.0
    }

    /// Bridge: create a `CanId` from an `ExprId`'s raw index.
    ///
    /// Used by backends that haven't migrated to `CanonResult` yet (`ori_arc`).
    /// The resulting `CanId` carries the same raw index as the `ExprId`, which
    /// the backend interprets in its own context.
    ///
    /// This will be removed once the ARC backend migrates to `CanonResult` (07.2).
    #[inline]
    pub const fn from_expr_id(id: crate::ExprId) -> Self {
        Self(id.raw())
    }

    /// Bridge: convert back to an `ExprId` raw index.
    ///
    /// Used by backends that haven't migrated to `CanonResult` yet.
    /// Will be removed once all backends use `CanonResult` (07.2).
    #[inline]
    pub const fn to_expr_id(self) -> crate::ExprId {
        crate::ExprId::new(self.0)
    }

    /// Returns `true` if this is a valid (non-sentinel) ID.
    #[inline]
    pub const fn is_valid(self) -> bool {
        self.0 != u32::MAX
    }
}

impl Hash for CanId {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

impl fmt::Debug for CanId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if *self == Self::INVALID {
            write!(f, "CanId::INVALID")
        } else {
            write!(f, "CanId({})", self.0)
        }
    }
}

impl Default for CanId {
    fn default() -> Self {
        Self::INVALID
    }
}

// Range newtypes into `CanArena` storage. Distinct index spaces (prevents
// cross-use); shape generated by the crate-internal `define_range!` SSOT.
//
// - `CanRange`: expression lists (args, list elements, block stmts, tuple
//   elements) into `expr_lists`. Layout matches `ExprRange`.
// - `CanMapEntryRange`: map entries (key-value pairs).
// - `CanFieldRange`: struct field initializers (name + value).
define_range!(CanRange, CanMapEntryRange, CanFieldRange);

/// Index into a [`CanArena`](super::CanArena)'s binding pattern storage.
///
/// Replaces `BindingPatternId` (which indexes `ExprArena.binding_patterns`)
/// with a canonical equivalent that keeps the IR self-contained.
#[derive(Copy, Clone, Eq, PartialEq, Hash)]
#[repr(transparent)]
pub struct CanBindingPatternId(u32);

impl CanBindingPatternId {
    #[inline]
    pub const fn new(index: u32) -> Self {
        Self(index)
    }

    #[inline]
    pub const fn index(self) -> usize {
        self.0 as usize
    }

    #[inline]
    pub const fn raw(self) -> u32 {
        self.0
    }
}

impl fmt::Debug for CanBindingPatternId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "CanBindingPatternId({})", self.0)
    }
}

// `CanBindingPatternRange`: binding pattern IDs in `binding_pattern_lists`
// (`Tuple`/`List` sub-patterns). `CanFieldBindingRange`: field bindings in
// `field_bindings`. Shape generated by the `define_range!` SSOT.
define_range!(CanBindingPatternRange, CanFieldBindingRange);
