//! `byte` type definition.

use crate::{
    MemoryStrategy, MethodDef, OpDefs, OpStrategy, Ownership, ParamDef, ReturnTag, TypeDef,
    TypeParamArity, TypeTag,
};

static SELF_PARAM: [ParamDef; 1] = [ParamDef::SELF_TYPE];

static BYTE_METHODS: &[MethodDef] = &[
    MethodDef::primitive(
        "add",
        &SELF_PARAM,
        ReturnTag::SelfType,
        Some("Add"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "bit_and",
        &SELF_PARAM,
        ReturnTag::SelfType,
        Some("BitAnd"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "bit_not",
        &[],
        ReturnTag::SelfType,
        Some("BitNot"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "bit_or",
        &SELF_PARAM,
        ReturnTag::SelfType,
        Some("BitOr"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "bit_xor",
        &SELF_PARAM,
        ReturnTag::SelfType,
        Some("BitXor"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "clone",
        &[],
        ReturnTag::SelfType,
        Some("Clone"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "compare",
        &SELF_PARAM,
        ReturnTag::Concrete(TypeTag::Ordering),
        Some("Comparable"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "debug",
        &[],
        ReturnTag::Concrete(TypeTag::Str),
        Some("Debug"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "div",
        &SELF_PARAM,
        ReturnTag::SelfType,
        Some("Div"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "equals",
        &SELF_PARAM,
        ReturnTag::Concrete(TypeTag::Bool),
        Some("Eq"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "hash",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        Some("Hashable"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_ascii",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_ascii_alpha",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_ascii_digit",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_ascii_whitespace",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "mul",
        &SELF_PARAM,
        ReturnTag::SelfType,
        Some("Mul"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "rem",
        &SELF_PARAM,
        ReturnTag::SelfType,
        Some("Rem"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "shl",
        &SELF_PARAM,
        ReturnTag::SelfType,
        Some("Shl"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "shr",
        &SELF_PARAM,
        ReturnTag::SelfType,
        Some("Shr"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "sub",
        &SELF_PARAM,
        ReturnTag::SelfType,
        Some("Sub"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_char",
        &[],
        ReturnTag::Concrete(TypeTag::Char),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_int",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_str",
        &[],
        ReturnTag::Concrete(TypeTag::Str),
        Some("Printable"),
        Ownership::Borrow,
    ),
];

pub static BYTE: TypeDef = TypeDef {
    tag: TypeTag::Byte,
    name: "byte",
    memory: MemoryStrategy::Copy,
    type_params: TypeParamArity::Fixed(0),
    methods: BYTE_METHODS,
    operators: OpDefs {
        add: OpStrategy::IntInstr,
        sub: OpStrategy::IntInstr,
        mul: OpStrategy::IntInstr,
        div: OpStrategy::IntInstr,
        rem: OpStrategy::IntInstr,
        floor_div: OpStrategy::Unsupported,
        eq: OpStrategy::IntInstr,
        neq: OpStrategy::IntInstr,
        lt: OpStrategy::UnsignedCmp,
        gt: OpStrategy::UnsignedCmp,
        lt_eq: OpStrategy::UnsignedCmp,
        gt_eq: OpStrategy::UnsignedCmp,
        neg: OpStrategy::Unsupported,
        not: OpStrategy::Unsupported,
        bit_and: OpStrategy::IntInstr,
        bit_or: OpStrategy::IntInstr,
        bit_xor: OpStrategy::IntInstr,
        bit_not: OpStrategy::IntInstr,
        shl: OpStrategy::IntInstr,
        shr: OpStrategy::IntInstr,
    },
};
