//! `char` type definition.

use crate::{
    MemoryStrategy, MethodDef, OpDefs, OpStrategy, Ownership, ParamDef, ReturnTag, TypeDef,
    TypeParamArity, TypeTag,
};

static SELF_PARAM: [ParamDef; 1] = [ParamDef::SELF_TYPE];

static CHAR_METHODS: &[MethodDef] = &[
    MethodDef::primitive(
        "clone",
        &[],
        ReturnTag::SelfType,
        Some("Clone"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "compare",
        &SELF_PARAM,
        ReturnTag::Concrete(TypeTag::Ordering),
        Some("Comparable"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "debug",
        &[],
        ReturnTag::Concrete(TypeTag::Str),
        Some("Debug"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "equals",
        &SELF_PARAM,
        ReturnTag::Concrete(TypeTag::Bool),
        Some("Eq"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "hash",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        Some("Hashable"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_alpha",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_ascii",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_digit",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_lowercase",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_uppercase",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_whitespace",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_byte",
        &[],
        ReturnTag::Concrete(TypeTag::Byte),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_int",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_lowercase",
        &[],
        ReturnTag::Concrete(TypeTag::Char),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_str",
        &[],
        ReturnTag::Concrete(TypeTag::Str),
        Some("Printable"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_uppercase",
        &[],
        ReturnTag::Concrete(TypeTag::Char),
        None,
        Ownership::Borrow,
    ),
];

pub static CHAR: TypeDef = TypeDef {
    tag: TypeTag::Char,
    name: "char",
    memory: MemoryStrategy::Copy,
    type_params: TypeParamArity::Fixed(0),
    methods: CHAR_METHODS,
    operators: OpDefs {
        add: OpStrategy::Unsupported,
        sub: OpStrategy::Unsupported,
        mul: OpStrategy::Unsupported,
        div: OpStrategy::Unsupported,
        rem: OpStrategy::Unsupported,
        floor_div: OpStrategy::Unsupported,
        eq: OpStrategy::IntInstr,
        neq: OpStrategy::IntInstr,
        lt: OpStrategy::UnsignedCmp,
        gt: OpStrategy::UnsignedCmp,
        lt_eq: OpStrategy::UnsignedCmp,
        gt_eq: OpStrategy::UnsignedCmp,
        neg: OpStrategy::Unsupported,
        not: OpStrategy::Unsupported,
        bit_and: OpStrategy::Unsupported,
        bit_or: OpStrategy::Unsupported,
        bit_xor: OpStrategy::Unsupported,
        bit_not: OpStrategy::Unsupported,
        shl: OpStrategy::Unsupported,
        shr: OpStrategy::Unsupported,
    },
};
