//! `float` type definition.

use crate::{
    MemoryStrategy, MethodDef, OpDefs, OpStrategy, Ownership, ReturnTag, TypeDef, TypeParamArity,
    TypeTag, ONE_SELF_COPY, TWO_SELF_COPY,
};

static FLOAT_METHODS: &[MethodDef] = &[
    MethodDef::primitive(
        "abs",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "acos",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "add",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("Add"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "asin",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "atan",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "atan2",
        &ONE_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "cbrt",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "ceil",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "clamp",
        &TWO_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "clone",
        &[],
        ReturnTag::SelfType,
        Some("Clone"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "compare",
        &ONE_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Ordering),
        Some("Comparable"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "cos",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "debug",
        &[],
        ReturnTag::Concrete(TypeTag::Str),
        Some("Debug"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "div",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("Div"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "equals",
        &ONE_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Bool),
        Some("Eq"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "exp",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "floor",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "hash",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        Some("Hashable"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_finite",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_infinite",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_nan",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_negative",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_normal",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_positive",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_zero",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "ln",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "log10",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "log2",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "max",
        &ONE_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "min",
        &ONE_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "mul",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("Mul"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "neg",
        &[],
        ReturnTag::SelfType,
        Some("Neg"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "pow",
        &ONE_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "rem",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("Rem"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "round",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "signum",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "sin",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "sqrt",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "sub",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("Sub"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "tan",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_int",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_str",
        &[],
        ReturnTag::Concrete(TypeTag::Str),
        Some("Printable"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "trunc",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
];

pub static FLOAT: TypeDef = TypeDef {
    tag: TypeTag::Float,
    name: "float",
    memory: MemoryStrategy::Copy,
    type_params: TypeParamArity::Fixed(0),
    methods: FLOAT_METHODS,
    operators: OpDefs {
        add: OpStrategy::FloatInstr,
        sub: OpStrategy::FloatInstr,
        mul: OpStrategy::FloatInstr,
        div: OpStrategy::FloatInstr,
        rem: OpStrategy::FloatInstr,
        floor_div: OpStrategy::Unsupported,
        eq: OpStrategy::FloatInstr,
        neq: OpStrategy::FloatInstr,
        lt: OpStrategy::FloatInstr,
        gt: OpStrategy::FloatInstr,
        lt_eq: OpStrategy::FloatInstr,
        gt_eq: OpStrategy::FloatInstr,
        neg: OpStrategy::FloatInstr,
        not: OpStrategy::Unsupported,
        bit_and: OpStrategy::Unsupported,
        bit_or: OpStrategy::Unsupported,
        bit_xor: OpStrategy::Unsupported,
        bit_not: OpStrategy::Unsupported,
        shl: OpStrategy::Unsupported,
        shr: OpStrategy::Unsupported,
    },
};
