//! `int` type definition.

use crate::{
    MemoryStrategy, MethodDef, OpDefs, OpStrategy, Ownership, ReturnTag, TypeDef, TypeParamArity,
    TypeTag, ONE_SELF_COPY, TWO_SELF_COPY,
};

static INT_METHODS: &[MethodDef] = &[
    MethodDef::primitive(
        "abs",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "add",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("Add"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "bit_and",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("BitAnd"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "bit_not",
        &[],
        ReturnTag::SelfType,
        Some("BitNot"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "bit_or",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("BitOr"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "bit_xor",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("BitXor"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "byte",
        &[],
        ReturnTag::Concrete(TypeTag::Byte),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "clamp",
        &TWO_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "clone",
        &[],
        ReturnTag::SelfType,
        Some("Clone"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "compare",
        &ONE_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Ordering),
        Some("Comparable"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "debug",
        &[],
        ReturnTag::Concrete(TypeTag::Str),
        Some("Debug"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "div",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("Div"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "equals",
        &ONE_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Bool),
        Some("Eq"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "f",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "floor_div",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("FloorDiv"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "hash",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        Some("Hashable"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "into",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_even",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_negative",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_odd",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_positive",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "is_zero",
        &[],
        ReturnTag::Concrete(TypeTag::Bool),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "max",
        &ONE_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "min",
        &ONE_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "mul",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("Mul"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "neg",
        &[],
        ReturnTag::SelfType,
        Some("Neg"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "pow",
        &ONE_SELF_COPY,
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "rem",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("Rem"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "shl",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("Shl"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "shr",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("Shr"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "signum",
        &[],
        ReturnTag::Concrete(TypeTag::Int),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "sub",
        &ONE_SELF_COPY,
        ReturnTag::SelfType,
        Some("Sub"),
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_byte",
        &[],
        ReturnTag::Concrete(TypeTag::Byte),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_float",
        &[],
        ReturnTag::Concrete(TypeTag::Float),
        None,
        Ownership::Borrow,
    ),
    MethodDef::primitive(
        "to_str",
        &[],
        ReturnTag::Concrete(TypeTag::Str),
        Some("Printable"),
        Ownership::Borrow,
    ),
];

pub static INT: TypeDef = TypeDef {
    tag: TypeTag::Int,
    name: "int",
    memory: MemoryStrategy::Copy,
    type_params: TypeParamArity::Fixed(0),
    methods: INT_METHODS,
    operators: OpDefs {
        add: OpStrategy::IntInstr,
        sub: OpStrategy::IntInstr,
        mul: OpStrategy::IntInstr,
        div: OpStrategy::IntInstr,
        rem: OpStrategy::IntInstr,
        floor_div: OpStrategy::IntInstr,
        eq: OpStrategy::IntInstr,
        neq: OpStrategy::IntInstr,
        lt: OpStrategy::IntInstr,
        gt: OpStrategy::IntInstr,
        lt_eq: OpStrategy::IntInstr,
        gt_eq: OpStrategy::IntInstr,
        neg: OpStrategy::IntInstr,
        not: OpStrategy::Unsupported,
        bit_and: OpStrategy::IntInstr,
        bit_or: OpStrategy::IntInstr,
        bit_xor: OpStrategy::IntInstr,
        bit_not: OpStrategy::IntInstr,
        shl: OpStrategy::IntInstr,
        shr: OpStrategy::IntInstr,
    },
};
