//! Shipped-lattice probe for the locality shipped-conformance cross-walk.
//!
//! Parses compiler/ori_arc/src/aims/lattice/dimensions.rs and
//! compiler/ori_arc/src/aims/contract/param.rs at build time via
//! syn AST traversal; emits two pub const declarations into
//! $OUT_DIR/shipped_lattice_probe.rs the checker's `shipped_lattice_probe`
//! module includes:
//!
//! pub const LATTICE_VARIANT_COUNT: usize = N;
//! pub const MAY_ESCAPE_IS_STORED: bool = B;
//!
//! Per the locality shipped-conformance cross-walk:
//! probe is the PRODUCER (emits the tuple); the cross-walk +
//! verdict-boundary tests are CONSUMERS (read the tuple to branch
//! divergent-pending vs pass).
//!
//! BANNED: shell grep.
//! BANNED: source-file `include!` reflection.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let compiler_root = locate_compiler_root();
    let dimensions_path = compiler_root
        .join("compiler/ori_arc/src/aims/lattice/dimensions.rs");
    let param_contract_path = compiler_root
        .join("compiler/ori_arc/src/aims/contract/param.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", dimensions_path.display());
    println!("cargo:rerun-if-changed={}", param_contract_path.display());

    let variant_count = probe_locality_variant_count(&dimensions_path);
    let may_escape_stored = probe_may_escape_is_stored(&param_contract_path);

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("shipped_lattice_probe.rs");

    let body = format!(
        "// Auto-generated by build.rs from compiler/ori_arc/ AST probe.\n\
         // DO NOT EDIT. Per the locality cross-walk SC4.\n\
         /// Number of variants in the shipped `Locality` enum (probed from `dimensions.rs` AST).\n\
         pub const LATTICE_VARIANT_COUNT: usize = {variant_count};\n\
         /// Whether `ParamContract.may_escape` is a stored field (probed from `contract/param.rs` AST).\n\
         pub const MAY_ESCAPE_IS_STORED: bool = {may_escape_stored};\n"
    );

    fs::write(&out_path, body).expect("failed to write shipped_lattice_probe.rs");
}

/// Walk up from `CARGO_MANIFEST_DIR` until we find a directory containing
/// `compiler/ori_arc/` — the repo root that holds the shipped AIMS lattice
/// surface this crate probes.
fn locate_compiler_root() -> PathBuf {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR not set");
    let mut cur = PathBuf::from(manifest_dir);
    loop {
        if cur.join("compiler/ori_arc").is_dir() {
            return cur;
        }
        if !cur.pop() {
            panic!(
                "build.rs could not locate a directory containing \
                 compiler/ori_arc/ starting from CARGO_MANIFEST_DIR"
            );
        }
    }
}

/// Parse `dimensions.rs` and count variants of `enum Locality`.
fn probe_locality_variant_count(path: &Path) -> usize {
    let src = fs::read_to_string(path).unwrap_or_else(|e| {
        panic!("failed to read {}: {}", path.display(), e)
    });
    let file = syn::parse_file(&src).unwrap_or_else(|e| {
        panic!("failed to parse {} as Rust: {}", path.display(), e)
    });

    for item in &file.items {
        if let syn::Item::Enum(item_enum) = item {
            if item_enum.ident == "Locality" {
                return item_enum.variants.len();
            }
        }
    }
    panic!(
        "probe: `enum Locality` not found in {}; \
         shipped lattice surface drifted away from the locality cross-walk probe contract",
        path.display()
    );
}

/// Parse `contract/param.rs` and detect whether `struct ParamContract`
/// carries `may_escape` as a stored field. Returns `true` if a field named
/// `may_escape` exists on the struct; `false` otherwise (e.g., only
/// `fn may_escape(&self) -> _` impl remains after the locality work).
fn probe_may_escape_is_stored(path: &Path) -> bool {
    let src = fs::read_to_string(path).unwrap_or_else(|e| {
        panic!("failed to read {}: {}", path.display(), e)
    });
    let file = syn::parse_file(&src).unwrap_or_else(|e| {
        panic!("failed to parse {} as Rust: {}", path.display(), e)
    });

    for item in &file.items {
        if let syn::Item::Struct(item_struct) = item {
            if item_struct.ident == "ParamContract" {
                if let syn::Fields::Named(fields) = &item_struct.fields {
                    for field in &fields.named {
                        if let Some(ident) = &field.ident {
                            if ident == "may_escape" {
                                return true;
                            }
                        }
                    }
                }
                return false;
            }
        }
    }
    panic!(
        "probe: `struct ParamContract` not found in {}; \
         shipped contract surface drifted away from the locality cross-walk probe contract",
        path.display()
    );
}
