//! Human-readable display and fixed lexeme dispatch tables for `RawTag`.
//!
//! Extracted from `tag/mod.rs` to keep the parent module under the 500-line limit.
//! These are pure lookup functions with no state — just large match dispatch tables.

use super::RawTag;

impl RawTag {
    /// Returns the fixed lexeme for this tag, if it has one.
    ///
    /// Operators and delimiters have fixed lexemes. Identifiers, literals,
    /// and error tokens return `None` (their text varies).
    #[must_use]
    pub fn lexeme(self) -> Option<&'static str> {
        match self {
            Self::Plus => Some("+"),
            Self::Minus => Some("-"),
            Self::Star => Some("*"),
            Self::Slash => Some("/"),
            Self::Percent => Some("%"),
            Self::Caret => Some("^"),
            Self::Ampersand => Some("&"),
            Self::Pipe => Some("|"),
            Self::Tilde => Some("~"),
            Self::Bang => Some("!"),
            Self::Equal => Some("="),
            Self::Less => Some("<"),
            Self::Greater => Some(">"),
            Self::Dot => Some("."),
            Self::Question => Some("?"),
            Self::EqualEqual => Some("=="),
            Self::BangEqual => Some("!="),
            Self::LessEqual => Some("<="),
            Self::AmpersandAmpersand => Some("&&"),
            Self::PipePipe => Some("||"),
            Self::Arrow => Some("->"),
            Self::FatArrow => Some("=>"),
            Self::DotDot => Some(".."),
            Self::DotDotEqual => Some("..="),
            Self::DotDotDot => Some("..."),
            Self::ColonColon => Some("::"),
            Self::Shl => Some("<<"),
            Self::QuestionQuestion => Some("??"),
            // Compound assignment
            Self::PlusEq => Some("+="),
            Self::MinusEq => Some("-="),
            Self::StarEq => Some("*="),
            Self::SlashEq => Some("/="),
            Self::PercentEq => Some("%="),
            Self::AtEq => Some("@="),
            Self::AmpersandEq => Some("&="),
            Self::PipeEq => Some("|="),
            Self::CaretEq => Some("^="),
            Self::ShlEq => Some("<<="),
            Self::AmpersandAmpersandEq => Some("&&="),
            Self::PipePipeEq => Some("||="),
            Self::LeftParen => Some("("),
            Self::RightParen => Some(")"),
            Self::LeftBracket => Some("["),
            Self::RightBracket => Some("]"),
            Self::LeftBrace => Some("{"),
            Self::RightBrace => Some("}"),
            Self::Comma => Some(","),
            Self::Colon => Some(":"),
            Self::Semicolon => Some(";"),
            Self::At => Some("@"),
            Self::Hash => Some("#"),
            Self::Underscore => Some("_"),
            Self::Backslash => Some("\\"),
            Self::Dollar => Some("$"),
            Self::HashBracket => Some("#["),
            Self::HashBang => Some("#!"),
            Self::Newline => Some("\n"),
            _ => None,
        }
    }

    /// Returns a human-readable name for this tag.
    ///
    /// Used in diagnostic messages and debugging output.
    #[must_use]
    pub fn name(self) -> &'static str {
        match self {
            Self::Ident => "identifier",
            Self::Int => "integer literal",
            Self::Float => "float literal",
            Self::HexInt => "hex integer literal",
            Self::BinInt => "binary integer literal",
            Self::String => "string literal",
            Self::Char => "character literal",
            Self::Duration => "duration literal",
            Self::Size => "size literal",
            Self::TemplateHead => "template head",
            Self::TemplateMiddle => "template middle",
            Self::TemplateTail => "template tail",
            Self::TemplateComplete => "template literal",
            Self::FormatSpec => "format spec",
            Self::Plus => "`+`",
            Self::Minus => "`-`",
            Self::Star => "`*`",
            Self::Slash => "`/`",
            Self::Percent => "`%`",
            Self::Caret => "`^`",
            Self::Ampersand => "`&`",
            Self::Pipe => "`|`",
            Self::Tilde => "`~`",
            Self::Bang => "`!`",
            Self::Equal => "`=`",
            Self::Less => "`<`",
            Self::Greater => "`>`",
            Self::Dot => "`.`",
            Self::Question => "`?`",
            Self::EqualEqual => "`==`",
            Self::BangEqual => "`!=`",
            Self::LessEqual => "`<=`",
            Self::AmpersandAmpersand => "`&&`",
            Self::PipePipe => "`||`",
            Self::Arrow => "`->`",
            Self::FatArrow => "`=>`",
            Self::DotDot => "`..`",
            Self::DotDotEqual => "`..=`",
            Self::DotDotDot => "`...`",
            Self::ColonColon => "`::`",
            Self::Shl => "`<<`",
            Self::QuestionQuestion => "`??`",
            // Compound assignment
            Self::PlusEq => "`+=`",
            Self::MinusEq => "`-=`",
            Self::StarEq => "`*=`",
            Self::SlashEq => "`/=`",
            Self::PercentEq => "`%=`",
            Self::AtEq => "`@=`",
            Self::AmpersandEq => "`&=`",
            Self::PipeEq => "`|=`",
            Self::CaretEq => "`^=`",
            Self::ShlEq => "`<<=`",
            Self::AmpersandAmpersandEq => "`&&=`",
            Self::PipePipeEq => "`||=`",
            Self::LeftParen => "`(`",
            Self::RightParen => "`)`",
            Self::LeftBracket => "`[`",
            Self::RightBracket => "`]`",
            Self::LeftBrace => "`{`",
            Self::RightBrace => "`}`",
            Self::Comma => "`,`",
            Self::Colon => "`:`",
            Self::Semicolon => "`;`",
            Self::At => "`@`",
            Self::Hash => "`#`",
            Self::Underscore => "`_`",
            Self::Backslash => "`\\`",
            Self::Dollar => "`$`",
            Self::HashBracket => "`#[`",
            Self::HashBang => "`#!`",
            Self::Whitespace => "whitespace",
            Self::Newline => "newline",
            Self::LineComment => "line comment",
            Self::InvalidByte => "invalid byte",
            Self::UnterminatedString => "unterminated string",
            Self::UnterminatedChar => "unterminated character literal",
            Self::InvalidEscape => "invalid escape",
            Self::UnterminatedTemplate => "unterminated template",
            Self::InteriorNull => "interior null byte",
            Self::Eof => "end of file",
        }
    }
}
