//! `FileCheck`-style IR assertion tests.
//!
//! Compiles `.ori` files from `tests/codegen/`, captures LLVM IR, and
//! matches `// CHECK:` directives against the output. Uses the shared
//! `check` engine from `ori_test_harness`.
//!
//! **Function-scoped IR slicing**: Each test file may include a
//! `// @function: <name>` custom directive specifying which function's
//! IR to check. If absent, defaults to `_ori_main`. The captured module
//! IR is sliced to the target function via `extract_function_ir()` before
//! matching, ensuring CHECK-NOT patterns are truly function-scoped and
//! cannot false-positive on symbols from unrelated functions.

use crate::util::{compile_and_capture_ir, extract_function_ir};
use ori_test_harness::check::{run_checks, CheckMode};
use ori_test_harness::directive;
use std::path::Path;

/// Run a single `FileCheck` test: compile the source, capture IR, match directives.
///
/// Supports `// @function: <name>` to scope CHECK directives to a specific
/// function's IR (default: `_ori_main`). This prevents CHECK-NOT from
/// seeing patterns in unrelated functions, runtime declarations, or stdlib stubs.
fn run_filecheck(relative_path: &str) {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let test_path = manifest.join(relative_path);
    let source = std::fs::read_to_string(&test_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", test_path.display()));

    let parse_result = directive::parse_directives(&source);
    let directives = parse_result.directives;

    // Extract @function: directive — determines which function's IR to check.
    // Default: _ori_main (the entry point wrapper generated by the compiler).
    let target_fn = directives
        .iter()
        .find_map(|d| match &d.directive {
            directive::Directive::Custom { key, value } if key == "function" => {
                Some(value.as_str())
            }
            _ => None,
        })
        .unwrap_or("_ori_main");

    let check_directives: Vec<_> = directives
        .iter()
        .filter(|d| {
            matches!(
                d.directive,
                directive::Directive::Check { .. }
                    | directive::Directive::CheckNot { .. }
                    | directive::Directive::CheckLabel { .. }
                    | directive::Directive::CheckNext { .. }
            )
        })
        .cloned()
        .collect();

    assert!(
        !check_directives.is_empty(),
        "no CHECK directives in {}",
        test_path.display()
    );

    let full_ir = compile_and_capture_ir(&source);

    // Function-scoped IR slicing: feed only the target function's IR to the
    // matching engine. This ensures CHECK-NOT patterns cannot false-positive
    // on symbols from other functions, runtime declarations, or stdlib stubs.
    let ir = extract_function_ir(&full_ir, target_fn);

    let result = run_checks(ir, &check_directives, CheckMode::Matches);

    if !result.passed {
        let failures: Vec<String> = result.failures.iter().map(|f| format!("  {f}")).collect();
        panic!(
            "FileCheck failed for {}:\n{}\n\n--- IR (function: {}) ---\n{}",
            test_path.display(),
            failures.join("\n"),
            target_fn,
            &ir[..ir.len().min(2000)]
        );
    }
}

#[test]
fn filecheck_rc_simple_inc_dec() {
    run_filecheck("tests/codegen/rc_simple_inc_dec.ori");
}

#[test]
fn filecheck_rc_no_ops_for_int() {
    run_filecheck("tests/codegen/rc_no_ops_for_int.ori");
}

#[test]
fn filecheck_rc_string_copy_inc() {
    run_filecheck("tests/codegen/rc_string_copy_inc.ori");
}

#[test]
fn filecheck_cow_is_shared_check() {
    run_filecheck("tests/codegen/cow_is_shared_check.ori");
}

#[test]
fn filecheck_iterator_for_loop_drop() {
    run_filecheck("tests/codegen/iterator_for_loop_drop.ori");
}

#[test]
fn filecheck_abi_sret_struct_return() {
    run_filecheck("tests/codegen/abi_sret_struct_return.ori");
}

#[test]
fn filecheck_closure_capture_env() {
    run_filecheck("tests/codegen/closure_capture_env.ori");
}

#[test]
fn filecheck_closure_no_env_for_empty_capture() {
    run_filecheck("tests/codegen/closure_no_env_for_empty_capture.ori");
}

#[test]
fn filecheck_rc_list_of_strings_cleanup() {
    run_filecheck("tests/codegen/rc_list_of_strings_cleanup.ori");
}

#[test]
fn filecheck_rc_no_ops_for_bool() {
    run_filecheck("tests/codegen/rc_no_ops_for_bool.ori");
}

#[test]
fn filecheck_iterator_break_cleanup() {
    run_filecheck("tests/codegen/iterator_break_cleanup.ori");
}

#[test]
fn filecheck_abi_void_return() {
    run_filecheck("tests/codegen/abi_void_return.ori");
}
