#!/usr/bin/env python3
"""LLVM IR parser for Code Journey metric extraction.

Parses textual LLVM IR (from ORI_DUMP_AFTER_LLVM=1) into structured
per-function data usable by all metric extractors.

Requires Python 3.10+ for union type syntax.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from ir_parser_internal import (
    ASSIGN_RE,
    ATTR_GROUP_RE,
    BLOCK_LABEL_RE,
    GLOBAL_RE,
    METADATA_RE,
    parse_attr_set,
    parse_function_header,
)


# ---------------------------------------------------------------------------
# Data Model
# ---------------------------------------------------------------------------

@dataclass
class Instruction:
    """A single LLVM IR instruction."""
    text: str           # Full instruction text (whitespace-stripped, no comments)
    opcode: str         # First keyword: "call", "br", "ret", "extractvalue", etc.
    result: str | None  # %register name if assignment, else None


@dataclass
class BasicBlock:
    """A basic block within a function."""
    label: str
    instructions: list[Instruction] = field(default_factory=list)


@dataclass
class Function:
    """An LLVM IR function (definition or declaration)."""
    name: str                        # Clean identifier (no @, no quotes)
    raw_name: str                    # Full LLVM name with @ (and quotes if present)
    is_definition: bool              # define vs declare
    calling_convention: str          # "fastcc", "ccc" (default), etc.
    return_type: str                 # "i64", "void", "{ i64, i1 }", etc.
    attributes: set[str]             # Resolved: {"nounwind", "uwtable", "noundef", ...}
    attribute_group_refs: list[int]  # Raw refs: [0, 2] for #0 #2
    blocks: list[BasicBlock]         # Empty for declarations
    param_attributes: list[set[str]]  # Per-parameter attributes
    param_types: list[str]           # ["i64", "ptr", ...]

    @property
    def is_user_function(self) -> bool:
        """User-defined function (subject to scoring).

        Excludes compiler-generated functions:
        - _ori_drop$* — destructors (called when RC reaches zero)
        - _ori_*$eq — derived trait methods (generated by #derive)
          are INCLUDED (they ARE user-visible codegen)
        """
        if not self.is_definition:
            return False
        if not self.name.startswith("_ori_"):
            return False
        # Drop functions are compiler plumbing, not user code.
        # They naturally have 0 inc / 1 dec (ori_rc_free), which is correct
        # behavior for a destructor but would flag as "unbalanced" in scoring.
        if "_ori_drop$" in self.name:
            return False
        # Element dec/inc functions are called N times from collection cleanup
        # (once per element). Static call-site counting always shows deficit
        # (1 dec call site, N runtime invocations). Same pattern as drop fns.
        if "_ori_elem_dec$" in self.name or "_ori_elem_inc$" in self.name:
            return False
        return True

    @property
    def is_runtime_decl(self) -> bool:
        """Runtime function declaration (ori_* without _ori_ prefix)."""
        return (not self.is_definition
                and self.name.startswith("ori_")
                and not self.name.startswith("_ori_"))

    @property
    def is_entry_called(self) -> bool:
        """@_ori_main -- called from C main wrapper, uses default cc."""
        return self.name == "_ori_main"

    @property
    def is_llvm_intrinsic(self) -> bool:
        """LLVM intrinsic (@llvm.*)."""
        return self.name.startswith("llvm.")

    @property
    def instruction_count(self) -> int:
        """Total instructions across all basic blocks."""
        return sum(len(b.instructions) for b in self.blocks)


@dataclass
class Module:
    """Parsed LLVM IR module."""
    functions: dict[str, Function] = field(default_factory=dict)
    globals: list[str] = field(default_factory=list)
    attribute_groups: dict[int, set[str]] = field(default_factory=dict)
    parse_errors: list[str] = field(default_factory=list)

    def user_functions(self) -> list[Function]:
        """Functions defined by user code (subject to scoring)."""
        return [f for f in self.functions.values() if f.is_user_function]

    def runtime_declarations(self) -> list[Function]:
        """Runtime function declarations (ori_*, not user code)."""
        return [f for f in self.functions.values() if f.is_runtime_decl]

    def llvm_intrinsics(self) -> list[Function]:
        """LLVM intrinsic declarations (@llvm.*)."""
        return [f for f in self.functions.values() if f.is_llvm_intrinsic]

    def is_entry_wrapper(self, f: Function) -> bool:
        """The C main() wrapper that calls @_ori_main."""
        return f.raw_name == "@main" and f.is_definition


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def parse_module(ir_text: str) -> Module:
    """Parse LLVM IR text into a Module.

    Handles empty input, malformed lines, and partial output gracefully.
    """
    module = Module()
    if not ir_text or not ir_text.strip():
        module.parse_errors.append("Empty IR input")
        return module

    lines = ir_text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped or stripped.startswith(';'):
            i += 1
            continue

        if stripped.startswith('source_filename') or stripped.startswith('target'):
            i += 1
            continue

        attr_match = ATTR_GROUP_RE.match(stripped)
        if attr_match:
            gid = int(attr_match.group(1))
            module.attribute_groups[gid] = parse_attr_set(attr_match.group(2).strip())
            i += 1
            continue

        if stripped.startswith('define '):
            func, end_idx = _parse_function_def(lines, i, module)
            if func:
                module.functions[func.raw_name] = func
            i = end_idx + 1
            continue

        if stripped.startswith('declare '):
            func = _parse_function_decl(stripped, module)
            if func:
                module.functions[func.raw_name] = func
            i += 1
            continue

        if GLOBAL_RE.match(stripped):
            module.globals.append(stripped)
            i += 1
            continue

        # Comdat groups: $name = comdat ...
        if stripped.startswith('$'):
            i += 1
            continue

        module.parse_errors.append(f"Line {i + 1}: unrecognized: {stripped[:80]}")
        i += 1

    _resolve_attributes(module)
    return module


# ---------------------------------------------------------------------------
# Internal Parsing (requires data classes)
# ---------------------------------------------------------------------------

def _parse_function_def(
    lines: list[str], start: int, module: Module
) -> tuple[Function | None, int]:
    """Parse a function definition (define ... { ... })."""
    header_line = lines[start].strip()

    parsed = parse_function_header(header_line)
    if not parsed:
        module.parse_errors.append(f"Line {start + 1}: failed to parse function header")
        i = start + 1
        while i < len(lines) and lines[i].strip() != '}':
            i += 1
        return None, i

    is_def, name, raw_name, cc, ret_type, p_types, p_attrs, g_refs, inl_attrs = parsed

    blocks: list[BasicBlock] = []
    current_block: BasicBlock | None = None
    i = start + 1

    while i < len(lines):
        stripped = lines[i].strip()

        if stripped == '}':
            if current_block:
                blocks.append(current_block)
            break

        if not stripped or stripped.startswith(';'):
            i += 1
            continue

        label_match = BLOCK_LABEL_RE.match(stripped)
        if label_match and not stripped.startswith('%'):
            if current_block:
                blocks.append(current_block)
            current_block = BasicBlock(label=label_match.group(1))
            i += 1
            continue

        if current_block is None:
            current_block = BasicBlock(label="entry")

        # Multi-line instructions: switch ... [ ... ] spans multiple lines
        if stripped.startswith('switch') and '[' in stripped and ']' not in stripped:
            full_text = stripped
            i += 1
            while i < len(lines):
                cont = lines[i].strip()
                if not cont or cont.startswith(';'):
                    i += 1
                    continue
                full_text += ' ' + cont
                if ']' in cont:
                    i += 1
                    break
                i += 1
            current_block.instructions.append(_parse_instruction(full_text))
            continue

        current_block.instructions.append(_parse_instruction(stripped))
        i += 1

    return Function(
        name=name,
        raw_name=raw_name,
        is_definition=True,
        calling_convention=cc,
        return_type=ret_type,
        attributes=set(inl_attrs),
        attribute_group_refs=g_refs,
        blocks=blocks,
        param_attributes=p_attrs,
        param_types=p_types,
    ), i


def _parse_function_decl(line: str, module: Module) -> Function | None:
    """Parse a function declaration (declare ...)."""
    parsed = parse_function_header(line)
    if not parsed:
        module.parse_errors.append(f"Failed to parse declaration: {line[:80]}")
        return None

    _, name, raw_name, cc, ret_type, p_types, p_attrs, g_refs, inl_attrs = parsed
    return Function(
        name=name,
        raw_name=raw_name,
        is_definition=False,
        calling_convention=cc,
        return_type=ret_type,
        attributes=set(inl_attrs),
        attribute_group_refs=g_refs,
        blocks=[],
        param_attributes=p_attrs,
        param_types=p_types,
    )


def _parse_instruction(text: str) -> Instruction:
    """Parse a single instruction line."""
    stripped = text.strip()

    # Strip inline comments
    semi = stripped.find(';')
    if semi >= 0:
        stripped = stripped[:semi].rstrip()

    # Strip trailing metadata (!dbg !42, !tbaa !5)
    stripped = METADATA_RE.sub('', stripped).rstrip(', ').rstrip()

    result = None
    opcode_text = stripped

    assign_match = ASSIGN_RE.match(stripped)
    if assign_match:
        result = assign_match.group(1)
        opcode_text = assign_match.group(2).strip()

    words = opcode_text.split()
    opcode = words[0] if words else ""

    return Instruction(text=stripped, opcode=opcode, result=result)


def _resolve_attributes(module: Module) -> None:
    """Resolve attribute group references to per-function attribute sets."""
    for func in module.functions.values():
        for ref in func.attribute_group_refs:
            if ref in module.attribute_groups:
                func.attributes |= module.attribute_groups[ref]
