#!/usr/bin/env bash
# rescore-all.sh — Re-score all existing journey results files with the
# deterministic extract-metrics.py pipeline. Produces a discrepancy report.
#
# Usage:
#     cd .claude/skills/code-journey
#     bash rescore-all.sh [--journeys-dir ../../plans/code-journeys]
#
# Output: rescore-report.md in the journey-scoring-algorithms plan directory
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
JOURNEYS_DIR="${1:-$(realpath "$SCRIPT_DIR/../../../plans/code-journeys")}"
REPORT_DIR="$(realpath "$SCRIPT_DIR/../../../plans/journey-scoring-algorithms")"
REPORT="$REPORT_DIR/rescore-report.md"
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

# Counters
total=0
scored=0
skipped=0
changed=0

cat > "$REPORT" << 'HEADER'
# Re-scoring Report

Automated comparison of old AI-judged scores vs new deterministic algorithmic scores.

Generated by `rescore-all.sh` using `extract-metrics.py` + `score.py`.

---

HEADER

for results_file in "$JOURNEYS_DIR"/*-results.md; do
    [ -f "$results_file" ] || continue
    total=$((total + 1))

    basename=$(basename "$results_file")
    journey_num=$(echo "$basename" | grep -oP '^\d+')

    # Extract frontmatter values
    expected=$(grep -m1 '^expected:' "$results_file" | awk '{print $2}')
    eval_exit=$(grep -m1 '^eval_result:' "$results_file" | awk '{print $2}')
    aot_exit=$(grep -m1 '^aot_result:' "$results_file" | awk '{print $2}')
    old_score=$(grep -m1 '^score:' "$results_file" | awk '{print $2}')
    slug=$(grep -m1 '^slug:' "$results_file" | awk '{print $2}')

    echo "--- Journey $journey_num ($slug) ---"

    # Extract old score_metrics from frontmatter
    old_instr_ratio=$(grep -m1 '  instruction_ratio:' "$results_file" | awk '{print $2}')
    old_arc_violations=$(grep -m1 '  arc_violations:' "$results_file" | awk '{print $2}')
    old_attr_applicable=$(grep -m1 '  attr_applicable:' "$results_file" | awk '{print $2}')
    old_attr_correct=$(grep -m1 '  attr_correct:' "$results_file" | awk '{print $2}')
    old_cf_defects=$(grep -m1 '  cf_defects:' "$results_file" | awk '{print $2}')
    old_ir_unjustified=$(grep -m1 '  ir_unjustified:' "$results_file" | awk '{print $2}')

    # Extract LLVM IR
    ir_file="$TMPDIR/journey${journey_num}_ir.txt"
    if ! python3 "$SCRIPT_DIR/extract_ir_from_results.py" "$results_file" -o "$ir_file" 2>/dev/null; then
        echo "  SKIP: No LLVM IR found"
        skipped=$((skipped + 1))
        echo "## Journey $journey_num: $slug" >> "$REPORT"
        echo "" >> "$REPORT"
        echo "**SKIPPED** — No embedded LLVM IR found in results file." >> "$REPORT"
        echo "" >> "$REPORT"
        continue
    fi

    # Run extract-metrics.py
    metrics_file="$TMPDIR/journey${journey_num}_metrics.json"
    aot_arg=""
    if [ -n "$aot_exit" ] && [ "$aot_exit" != "null" ]; then
        aot_arg="--aot-exit $aot_exit"
    fi

    python3 "$SCRIPT_DIR/extract-metrics.py" \
        --ir-file "$ir_file" \
        --eval-exit "$eval_exit" \
        $aot_arg \
        --expected "$expected" \
        2>/dev/null > "$metrics_file"

    # Extract new metrics from JSON
    new_instr_ratio=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(d['instruction_ratio'])")
    new_instr_ratio_max=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(d['instruction_ratio_max'])")
    new_arc_violations=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(d['arc_violations'])")
    new_attr_applicable=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(d['attr_applicable'])")
    new_attr_correct=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(d['attr_correct'])")
    new_cf_defects=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(d['cf_defects'])")
    new_ir_unjustified=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(d['ir_unjustified'])")

    # Run score.py to get new overall score
    new_arc_unbal=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(str(d['arc_has_unbalanced']).lower())")
    new_arc_scalar=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(str(d['arc_has_scalar_rc']).lower())")
    new_attr_wrong=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(str(d['attr_has_wrong']).lower())")
    new_cf_incorrect=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(str(d['cf_incorrect']).lower())")
    new_ir_incorrect=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(str(d['ir_incorrect']).lower())")
    new_bin_defects=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(d['bin_defects'])")
    new_bin_hard_fail=$(python3 -c "import json; d=json.load(open('$metrics_file')); print(str(d['bin_hard_fail']).lower())")

    score_json="$TMPDIR/journey${journey_num}_score.json"
    python3 "$SCRIPT_DIR/score.py" \
        --instruction-ratio "$new_instr_ratio" \
        --instruction-ratio-max "$new_instr_ratio_max" \
        --arc-violations "$new_arc_violations" \
        --arc-has-unbalanced "$new_arc_unbal" \
        --arc-has-scalar-rc "$new_arc_scalar" \
        --attr-applicable "$new_attr_applicable" \
        --attr-correct "$new_attr_correct" \
        --attr-has-wrong "$new_attr_wrong" \
        --cf-defects "$new_cf_defects" \
        --cf-incorrect "$new_cf_incorrect" \
        --ir-unjustified "$new_ir_unjustified" \
        --ir-incorrect "$new_ir_incorrect" \
        --bin-defects "$new_bin_defects" \
        --bin-hard-fail "$new_bin_hard_fail" \
        2>/dev/null > "$score_json"

    new_score=$(python3 -c "import json; d=json.load(open('$score_json')); print(d['overall'])")

    # Compare
    _tag() {
        if [ "$1" = "$2" ]; then echo "SAME"; else echo "CHANGED"; fi
    }

    tag_ratio=$(_tag "$old_instr_ratio" "$new_instr_ratio")
    tag_arc=$(_tag "$old_arc_violations" "$new_arc_violations")
    tag_attr_app=$(_tag "$old_attr_applicable" "$new_attr_applicable")
    tag_attr_cor=$(_tag "$old_attr_correct" "$new_attr_correct")
    tag_cf=$(_tag "$old_cf_defects" "$new_cf_defects")
    tag_ir=$(_tag "$old_ir_unjustified" "$new_ir_unjustified")
    tag_overall=$(_tag "$old_score" "$new_score")

    if [ "$tag_overall" = "CHANGED" ]; then
        changed=$((changed + 1))
    fi
    scored=$((scored + 1))

    echo "  Old score: $old_score  →  New: $new_score  [$tag_overall]"

    # Write report entry
    cat >> "$REPORT" << EOF
## Journey $journey_num: $slug

| Metric | Old | New | Status |
|--------|-----|-----|--------|
| instruction_ratio | $old_instr_ratio | $new_instr_ratio | $tag_ratio |
| arc_violations | $old_arc_violations | $new_arc_violations | $tag_arc |
| attr_applicable | $old_attr_applicable | $new_attr_applicable | $tag_attr_app |
| attr_correct | $old_attr_correct | $new_attr_correct | $tag_attr_cor |
| cf_defects | $old_cf_defects | $new_cf_defects | $tag_cf |
| ir_unjustified | $old_ir_unjustified | $new_ir_unjustified | $tag_ir |
| **Overall Score** | **$old_score** | **$new_score** | **$tag_overall** |

EOF

    if [ "$tag_overall" = "CHANGED" ]; then
        echo "**Explanation**: Score changed from $old_score to $new_score." >> "$REPORT"
        echo "" >> "$REPORT"

        # Add detailed per-metric explanations for changed values
        if [ "$tag_ratio" = "CHANGED" ]; then
            echo "- **instruction_ratio**: Old AI computed $old_instr_ratio (likely using unchecked ideal). New algorithm computes $new_instr_ratio (overflow checking IS part of ideal for Ori)." >> "$REPORT"
        fi
        if [ "$tag_attr_app" = "CHANGED" ] || [ "$tag_attr_cor" = "CHANGED" ]; then
            echo "- **attributes**: Old AI counted $old_attr_applicable applicable / $old_attr_correct correct. New algorithm found $new_attr_applicable applicable / $new_attr_correct correct (deterministic per-param noundef checking, per-function rule table)." >> "$REPORT"
        fi
        if [ "$tag_cf" = "CHANGED" ]; then
            echo "- **cf_defects**: Old: $old_cf_defects, New: $new_cf_defects (algorithmic empty-block and redundant-branch detection)." >> "$REPORT"
        fi
        if [ "$tag_ir" = "CHANGED" ]; then
            echo "- **ir_unjustified**: Old: $old_ir_unjustified, New: $new_ir_unjustified (pattern-based unjustified instruction detection)." >> "$REPORT"
        fi
        echo "" >> "$REPORT"
    else
        echo "No discrepancies — old and new scores match." >> "$REPORT"
        echo "" >> "$REPORT"
    fi

    echo "---" >> "$REPORT"
    echo "" >> "$REPORT"

done

# Summary
cat >> "$REPORT" << EOF
## Summary

| Stat | Count |
|------|-------|
| Total results files | $total |
| Successfully scored | $scored |
| Skipped (no IR) | $skipped |
| Score changed | $changed |
| Score unchanged | $((scored - changed)) |
EOF

echo ""
echo "=== RESCORE COMPLETE ==="
echo "Total: $total | Scored: $scored | Skipped: $skipped | Changed: $changed"
echo "Report: $REPORT"
