//! Derived trait method compilation.
//!
//! Derived methods (Eq, Clone, Hashable, Printable) are generated by direct
//! `derive_codegen` synthesis rather than the ARC pipeline, and registered in
//! `method_functions` for normal method dispatch.

use ori_ir::Name;
use ori_types::Idx;

use super::FunctionCompiler;
use crate::codegen::abi::FunctionAbi;
use crate::codegen::value_id::{FunctionId, ValueId};

impl<'scx: 'ctx, 'ctx> FunctionCompiler<'_, 'scx, 'ctx, '_> {
    /// Compile derived trait methods for types with `#[derive(...)]`.
    ///
    /// Generates synthetic LLVM functions for derived traits (Eq, Clone,
    /// Hashable, Printable) and registers them in `method_functions` for
    /// normal method dispatch.
    pub fn compile_derives(
        &mut self,
        module: &ori_ir::Module,
        user_types: &[ori_types::TypeEntry],
    ) {
        super::super::derive_codegen::compile_derives(self, module, user_types);
    }

    /// Declare a derived method LLVM function, create entry block, bind params.
    ///
    /// Delegates to [`Self::declare_function_llvm`] for declaration and
    /// [`Self::load_param_values`] for parameter loading. Registers the method
    /// in `method_functions` and `type_idx_to_name` for dispatch.
    ///
    /// Returns `(func_id, self_value, other_param_values)`.
    pub(crate) fn declare_and_bind_derive(
        &mut self,
        symbol: &str,
        abi: &FunctionAbi,
        type_name: Name,
        method_name: Name,
        type_idx: Idx,
    ) -> (FunctionId, ValueId, Vec<ValueId>) {
        let func_id = self.declare_function_llvm(symbol, abi);

        let entry = self.builder.append_block(func_id, "entry");
        self.builder.position_at_end(entry);
        self.builder.set_current_function(func_id);

        let values = self.load_param_values(func_id, abi);
        let self_value = values
            .first()
            .copied()
            .unwrap_or_else(|| self.builder.const_i64(0));
        let other_vals = values.into_iter().skip(1).collect();

        self.codegen_ctx
            .method_functions
            .insert((type_name, method_name), (func_id, abi.clone()));
        self.codegen_ctx
            .type_idx_to_name
            .insert(type_idx, type_name);

        // Verify round-trip: registrations are immediately retrievable.
        debug_assert!(
            self.codegen_ctx
                .method_functions
                .contains_key(&(type_name, method_name)),
            "derive: method_functions registration failed for {}.{}",
            self.interner.lookup(type_name),
            self.interner.lookup(method_name),
        );
        debug_assert!(
            self.codegen_ctx.type_idx_to_name.contains_key(&type_idx),
            "derive: type_idx_to_name registration failed for '{}' (Idx {:?})",
            self.interner.lookup(type_name),
            type_idx,
        );

        (func_id, self_value, other_vals)
    }
}
